/**
 * COSMIC TO PLANCK SCALE SCIENTIFIC DATABASE 2.0
 * Comprehensive, mathematically validated dataset covering 62 Orders of Magnitude
 * Physics Formulas: t = d / c, Planck limit, relativistic comoving distances,
 * Fundamental force dominance, Instrument ladder, and Human transit equivalents.
 * ZERO EMOJIS: All visual icons rendered via pure vector SVG.
 */

export const SCALE_DOMAINS = [
  { id: 'cosmic', min: 21, max: 27, nameEn: 'Cosmic Superstructures', nameBn: 'মহাজাগতিক মহাকাঠামো', color: '#8b5cf6', iconKey: 'universe' },
  { id: 'astrophysical', min: 11, max: 20, nameEn: 'Galaxies & Stellar Realm', nameBn: 'ছায়াপথ ও নক্ষত্রজগৎ', color: '#3b82f6', iconKey: 'galaxy' },
  { id: 'planetary', min: 5, max: 10, nameEn: 'Solar System & Planets', nameBn: 'সৌরজগৎ ও গ্রহমণ্ডল', color: '#06b6d4', iconKey: 'planet' },
  { id: 'macro', min: -3, max: 4, nameEn: 'Human & Terrestrial Scale', nameBn: 'মানবীয় ও পার্থিব স্কেল', color: '#10b981', iconKey: 'human' },
  { id: 'micro', min: -7, max: -4, nameEn: 'Microscopic & Cellular', nameBn: 'আণুবীক্ষণিক ও কোষীয় জগৎ', color: '#f59e0b', iconKey: 'microscope' },
  { id: 'nano', min: -10, max: -8, nameEn: 'Nanoscale & Molecular', nameBn: 'ন্যানোস্কেল ও আণবিক জগৎ', color: '#ec4899', iconKey: 'dna' },
  { id: 'nuclear', min: -18, max: -11, nameEn: 'Atomic Nucleus & Quarks', nameBn: 'পারমাণবিক নিউক্লিয়াস ও কণা', color: '#ef4444', iconKey: 'atom' },
  { id: 'planck', min: -35, max: -19, nameEn: 'Theoretical Desert & Planck Limit', nameBn: 'তাত্ত্বিক মরুভূমি ও প্ল্যাঙ্ক সীমা', color: '#a855f7', iconKey: 'planck' }
];

export const COSMIC_OBJECTS = [
  {
    order: 26.94,
    id: 'observable_universe',
    nameEn: 'The Observable Universe',
    nameBn: 'দৃশ্যমান মহাবিশ্ব',
    sizeMeters: 8.8e26,
    sizeFormatted: '8.8 × 10²⁶ m (Diameter: 93 Billion LY | Radius: 46.5 Billion LY)',
    sizeFormattedBn: '৮.৮ × ১০²⁶ মিটার (ব্যাস: ৯৩ বিলিয়ন আলোকবর্ষ | ব্যাসার্ধ: ৪৬.৫ বিলিয়ন)',
    lightTime: 'N/A (Comoving Distance)',
    lightTimeBn: 'N/A (প্রসারণশীল মহাবিশ্বের কো-মুভিং দূরত্ব)',
    truthTag: 'measured',
    truthBadgeEn: 'Verified Comoving Horizon (Radius: 46.5 Gly)',
    truthBadgeBn: 'পরিমাপকৃত দিগন্ত সীমা (ব্যাসার্ধ: ৪৬.৫ Gly)',
    dominantForce: 'gravity',
    dominantForceEn: 'Gravity & Dark Energy',
    dominantForceBn: 'মহাকর্ষ ও ডার্ক এনার্জি',
    instrumentEn: 'Cosmic Microwave Background (Planck / WMAP)',
    instrumentBn: 'কসমিক মাইক্রোওয়েভ ব্যাকগ্রাউন্ড (Planck স্যাটেলাইট)',
    blackHoleRadiusEn: 'Approximately 15 billion light years—suggesting our observable universe exists near its own horizon limits!',
    blackHoleRadiusBn: 'মহাবিশ্বের মোট ভর বিবেচনায় শোয়ার্জশিল্ড ব্যাসার্ধ প্রায় ১৫ বিলিয়ন আলোকবর্ষ—যা মহাবিশ্বের নিজস্ব দিগন্ত সীমার অনুরূপ!',
    humanTransit: {
      walk: 'অপ্রাসঙ্গিক (মহাবিশ্ব আলোর চেয়ে দ্রুত প্রসারিত হচ্ছে)',
      jet: 'অপ্রাসঙ্গিক',
      voyager: 'অপ্রাসঙ্গিক'
    },
    domain: 'cosmic',
    renderType: 'observable_universe',
    accentColor: '#818cf8',
    summaryEn: 'The spherical boundary of everything we can theoretically observe. Light has had 13.8 billion years to reach us, but cosmic expansion stretched the diameter to 93 billion light years (comoving distance). Contains over 2 trillion galaxies.',
    summaryBn: '১৩.৮ বিলিয়ন বছর আগের বিগ ব্যাং-এর পর থেকে যে সীমানা পর্যন্ত আলো আমাদের কাছে পৌঁছানোর সুযোগ পেয়েছে। স্থান-কালের ত্বরাণ্বিত প্রসারণের ফলে এর বর্তমান ব্যাস প্রায় ৯৩ বিলিয়ন আলোকবর্ষ (কো-মুভিং দূরত্ব)। এতে কমপক্ষে ২ ট্রিলিয়ন গ্যালাক্সি রয়েছে।',
    factEn: 'Why is it 93 billion light-years if the universe is only 13.8 billion years old? Because the space itself has been expanding continuously during light transit!',
    factBn: 'মহাবিশ্বের বয়স ১৩.৮ বিলিয়ন বছর হলেও এর ব্যাস ৯৩ বিলিয়ন আলোকবর্ষ কেন? কারণ আলো যখন আমাদের দিকে ছুটে আসছিল, স্থান-কাল নিজেই আলোর চেয়ে দ্রুতগতিতে প্রসারিত হচ্ছিল!',
    sources: 'Planck Collaboration 2018 / NASA WMAP'
  },
  {
    order: 26.0,
    id: 'hercules_great_wall',
    nameEn: 'Hercules-Corona Borealis Great Wall',
    nameBn: 'হারকিউলিস-করোনা বরিয়ালিস মহাপ্রাচীর',
    sizeMeters: 1.0e26,
    sizeFormatted: '1.0 × 10²⁶ m (~10 Billion Light Years)',
    sizeFormattedBn: '১.০ × ১০²⁶ মিটার (~১০ বিলিয়ন আলোকবর্ষ)',
    lightTime: '~10.5 Billion Years',
    lightTimeBn: '~১০.৫ বিলিয়ন বছর',
    truthTag: 'speculative',
    truthBadgeEn: 'Speculative / Disputed Existence',
    truthBadgeBn: 'অনুমান / অস্তিত্ব বিতর্কিত',
    dominantForce: 'gravity',
    dominantForceEn: 'Gravitational Filaments',
    dominantForceBn: 'মহাকর্ষীয় ফিলামেন্ট জাল',
    instrumentEn: 'Gamma-Ray Burst Mapping',
    instrumentBn: 'গামা-রে বিস্ফোরণ জরিপ',
    humanTransit: {
      walk: '৭.২ × ১০²⁵ বছর',
      jet: '৪.০ × ১০²৩ বছর',
      voyager: '৫.৯ × ১০²১ বছর'
    },
    domain: 'cosmic',
    renderType: 'super_wall',
    accentColor: '#c084fc',
    summaryEn: 'A colossal cosmic superstructure mapped by the concentration of gamma-ray bursts. Its existence is debated because standard cosmological models predict structures cannot exceed 1.2 billion light years.',
    summaryBn: 'দৃশ্যমান মহাবিশ্বের সম্ভাব্য বৃহত্তম একক মহাকাঠামো। গামা-রে বিস্ফোরণের বিস্তার দেখে চিহ্নিত এই কাঠামোটির অস্তিত্ব নিয়ে বিতর্ক রয়েছে, কারণ মহাজাগতিক নীতি অনুযায়ী এত বড় কাঠামো গড়ে ওঠা কঠিন।',
    factEn: 'If fully verified, it violates the Cosmological Principle which states the universe is homogeneous on large scales.',
    factBn: 'এটি যদি নিশ্চিত প্রমাণিত হয়, তবে তা সমসত্ত্ব মহাবিশ্ব নীতির সঙ্গে সরাসরি সংঘাতে জড়াবে!',
    sources: 'Horvath et al. (2014) / Gamma-Ray Burst Analysis'
  },
  {
    order: 25.0,
    id: 'cosmic_web',
    nameEn: 'The Cosmic Web & Boötes Void',
    nameBn: 'মহাজাগতিক জাল ও বুটস ভয়েড',
    sizeMeters: 1.0e25,
    sizeFormatted: '1.0 × 10²⁵ m (~1 Billion Light Years)',
    sizeFormattedBn: '১.০ × ১০²৫ মিটার (~১ বিলিয়ন আলোকবর্ষ)',
    lightTime: '~1.05 Billion Years',
    lightTimeBn: '~১.০৫ বিলিয়ন বছর',
    truthTag: 'measured',
    truthBadgeEn: 'Measured Filamentary Structure',
    truthBadgeBn: 'পরিমাপকৃত ফিলামেন্টারি কাঠামো',
    dominantForce: 'gravity',
    dominantForceEn: 'Dark Matter Gravitational Scaffolding',
    dominantForceBn: 'ডার্ক ম্যাটার মহাকর্ষীয় ভারা',
    instrumentEn: 'Sloan Digital Sky Survey (SDSS)',
    instrumentBn: 'স্লোন ডিজিটাল স্কাই সার্ভে (SDSS)',
    humanTransit: {
      walk: '৭.২ × ১০²৪ বছর',
      jet: '৪.০ × ১০²২ বছর',
      voyager: '৫.৯ × ১০২০ বছর'
    },
    domain: 'cosmic',
    renderType: 'cosmic_web',
    accentColor: '#38bdf8',
    summaryEn: 'The neural-network-like architecture of the universe where galaxies cluster along dark matter filaments separated by immense voids. The Boötes Void is 330 million light-years of near emptiness.',
    summaryBn: 'মহাবিশ্বের নিউরাল নেটওয়ার্কের মতো ফিলামেন্ট জাল যেখানে ডার্ক ম্যাটারের সুতো ধরে গ্যালাক্সিরা অবস্থান করে। এর মাঝে রয়েছে বুটস ভয়েডের মতো বিশাল শূন্যস্থান (৩৩০ মিলিয়ন আলোকবর্ষ)।',
    factEn: 'If the Milky Way was at the center of the Boötes Void, we would not have discovered other galaxies until the 1960s!',
    factBn: 'আমাদের আকাশগঙ্গা যদি বুটস ভয়েডের কেন্দ্রে থাকত, তবে ১৯৬০ সালের আগে আমরা অন্য কোনো গ্যালাক্সির অস্তিত্বই জানতে পারতাম না!',
    sources: 'Millennium Simulation / SDSS Surveys'
  },
  {
    order: 24.69,
    id: 'laniakea_supercluster',
    nameEn: 'Laniakea Supercluster',
    nameBn: 'লানিয়াকেয়া সুপারক্লাস্টার',
    sizeMeters: 4.9e24,
    sizeFormatted: '4.9 × 10²⁴ m (~520 Million Light Years)',
    sizeFormattedBn: '৪.৯ × ১০²⁴ মিটার (~৫২০ মিলিয়ন আলোকবর্ষ)',
    lightTime: '~518 Million Years',
    lightTimeBn: '~৫১৮ মিলিয়ন বছর',
    truthTag: 'measured',
    truthBadgeEn: 'Peculiar Velocity Mapped',
    truthBadgeBn: 'পরিমাপকৃত মহাকর্ষীয় অববাহিকা',
    dominantForce: 'gravity',
    dominantForceEn: 'Gravitational Attraction to Great Attractor',
    dominantForceBn: 'গ্রেট অ্যাট্রাক্টরের মহাকর্ষীয় টান',
    instrumentEn: 'Cosmicflows-2 Peculiar Velocity Mapping',
    instrumentBn: 'কসমিকফ্লো-২ বেগ প্রবাহ জরিপ',
    humanTransit: {
      walk: '৩.৫ × ১০২৪ বছর',
      jet: '১.৯ × ১০২২ বছর',
      voyager: '২.৯ × ১০২০ বছর'
    },
    domain: 'cosmic',
    renderType: 'supercluster',
    accentColor: '#a78bfa',
    summaryEn: 'Our home galactic supercluster containing 100,000 galaxies flowing toward the Great Attractor gravitational anomaly. The name means "immense heaven" in Hawaiian.',
    summaryBn: 'আমাদের গ্যালাক্সির অভিভাবক সুপারক্লাস্টার যার মধ্যে ১ লক্ষ গ্যালাক্সি রয়েছে। সব গ্যালাক্সি "গ্রেট অ্যাট্রাক্টর" নামক এক রহস্যময় মহাকর্ষীয় কেন্দ্রের দিকে ধাবিত হচ্ছে।',
    factEn: 'Laniakea is not gravitationally bound; dark energy will tear it apart before the galaxies ever converge.',
    factBn: 'লানিয়াকেয়া মহাকর্ষীয়ভাবে সম্পূর্ণ আবদ্ধ নয়; গ্যালাক্সিগুলো মিলিত হওয়ার আগেই ডার্ক এনার্জি একে ছিন্নভিন্ন করে দেবে!',
    sources: 'Tully et al. (Nature 2014)'
  },
  {
    order: 22.98,
    id: 'local_group',
    nameEn: 'The Local Group',
    nameBn: 'লোকাল গ্রুপ (স্থানীয় গ্যালাক্সি স্তবক)',
    sizeMeters: 9.5e22,
    sizeFormatted: '9.5 × 10²² m (~10 Million Light Years)',
    sizeFormattedBn: '৯.৫ × ১০²২ মিটার (~১০ মিলিয়ন আলোকবর্ষ)',
    lightTime: '~10.0 Million Years',
    lightTimeBn: '~১০.০ মিলিয়ন বছর',
    truthTag: 'measured',
    truthBadgeEn: 'Gravitationally Bound Group',
    truthBadgeBn: 'পরিমাপকৃত আবদ্ধ গ্যালাক্সি পরিবার',
    dominantForce: 'gravity',
    dominantForceEn: 'Mutual Gravitational Binding',
    dominantForceBn: 'পারস্পরিক মহাকর্ষীয় বন্ধন',
    instrumentEn: 'Optical Telescopes & Astrometry',
    instrumentBn: 'অপটিক্যাল টেলিস্কোপ ও অ্যাস্ট্রোমেট্রি',
    humanTransit: {
      walk: '৬.৮ × ১০²² বছর',
      jet: '৩.৮ × ১০২০ বছর',
      voyager: '৫.৬ × ১০১৮ বছর'
    },
    domain: 'cosmic',
    renderType: 'local_group',
    accentColor: '#60a5fa',
    summaryEn: 'A gravitationally bound collection of over 80 galaxies dominated by the Milky Way, Andromeda, and the Triangulum galaxy.',
    summaryBn: 'আমাদের গ্যালাক্সি পরিবারের মহাকর্ষীয় জোট। আকাশগঙ্গা, অ্যান্ড্রোমিডা ও ট্রায়াঙ্গুলাম গ্যালাক্সি সহ ৮০ টিরও বেশি গ্যালাক্সি এর সদস্য।',
    factEn: 'Andromeda is rushing toward the Milky Way at 110 km/s. They will collide in 4.5 billion years to form Milkdromeda!',
    factBn: 'অ্যান্ড্রোমিডা প্রতি সেকেন্ডে ১১০ কিমি বেগে আকাশগঙ্গার দিকে ধেয়ে আসছে। ৪.৫ বিলিয়ন বছর পর তাদের মিলন ঘটে তৈরি হবে মিল্কড্রোমিডা!',
    sources: 'van den Bergh (Cambridge Univ. Press)'
  },
  {
    order: 21.0,
    id: 'milky_way',
    nameEn: 'The Milky Way Galaxy',
    nameBn: 'আকাশগঙ্গা গ্যালাক্সি',
    sizeMeters: 9.5e20,
    sizeFormatted: '9.5 × 10²⁰ m (~100,000 Light Years)',
    sizeFormattedBn: '৯.৫ × ১০²⁰ মিটার (~১,০০,০০০ আলোকবর্ষ)',
    lightTime: '~100,400 Years',
    lightTimeBn: '~১,০০,৪০০ বছর',
    truthTag: 'measured',
    truthBadgeEn: 'Directly Mapped Spiral Galaxy',
    truthBadgeBn: 'পরিমাপকৃত সর্পিল গ্যালাক্সি',
    dominantForce: 'gravity',
    dominantForceEn: 'Central Supermassive Black Hole & Dark Matter Halo',
    dominantForceBn: 'কেন্দ্রীয় ব্ল্যাকহোল ও ডার্ক ম্যাটার মহাকর্ষ',
    instrumentEn: 'Gaia Space Observatory / Infrared Mapping',
    instrumentBn: 'গায়া স্পেস অবজারভেটরি ও ইনফ্রারেড ম্যাপিং',
    blackHoleRadiusEn: 'Compressing the galaxy\'s total mass (~1.5 trillion solar masses) yields an event horizon of ~0.3 light years.',
    blackHoleRadiusBn: 'সম্পূর্ণ গ্যালাক্সির ভর (~১.৫ ট্রিলিয়ন সৌরভর) ব্ল্যাকহোলে সংকুচিত করলে শোয়ার্জশিল্ড ব্যাসার্ধ হবে প্রায় ০.৩ আলোকবর্ষ।',
    humanTransit: {
      walk: '৬.৮ × ১০২০ বছর',
      jet: '৩.৮ × ১০১৮ বছর',
      voyager: '১.৭৭ বিলিয়ন (১৭০ কোটি) বছর'
    },
    domain: 'astrophysical',
    renderType: 'milky_way',
    accentColor: '#818cf8',
    summaryEn: 'A barred spiral galaxy containing 100 to 400 billion stars. At its core lies Sagittarius A*, a supermassive black hole of 4 million solar masses.',
    summaryBn: 'একটি ব্যারেড স্পাইরাল গ্যালাক্সি যাতে ১০০ থেকে ৪০০ বিলিয়ন নক্ষত্র রয়েছে। এর কেন্দ্রে রয়েছে স্যাজিটেরিয়াস এ* নামক ৪০ লক্ষ সৌরভরের সুপারম্যাসিভ ব্ল্যাকহোল।',
    factEn: 'Voyager 1 traveling at 17 km/s would take 1.77 billion years just to cross the Milky Way disk!',
    factBn: 'ভয়েজার-১ মহাকাশযানের গতিতে (১৭ কিমি/সেকেন্ড) আকাশগঙ্গার এক প্রান্ত থেকে অন্য প্রান্তে যেতে ১৭০ কোটি বছর লাগবে!',
    sources: 'ESA Gaia Survey 2022 / NASA'
  },
  {
    order: 17.36,
    id: 'orion_nebula',
    nameEn: 'Orion Nebula (M42)',
    nameBn: 'কালপুরুষ নীহারিকা (অরিয়ন নেবুলা)',
    sizeMeters: 2.3e17,
    sizeFormatted: '2.3 × 10¹⁷ m (~24 Light Years)',
    sizeFormattedBn: '২.৩ × ১০¹৭ মিটার (~২৪ আলোকবর্ষ)',
    lightTime: '~24.3 Years',
    lightTimeBn: '~২৪.৩ বছর',
    truthTag: 'measured',
    truthBadgeEn: 'Direct Observation Stellar Nursery',
    truthBadgeBn: 'পরিমাপকৃত নক্ষত্র প্রসূতিগার',
    dominantForce: 'gravity',
    dominantForceEn: 'Gravitational Collapse & Radiation Pressure',
    dominantForceBn: 'মহাকর্ষীয় সংকোচন ও বিকিরণ চাপ',
    instrumentEn: 'Hubble Space Telescope / James Webb',
    instrumentBn: 'হাবল ও জেমস ওয়েব টেলিস্কোপ',
    humanTransit: {
      walk: '১.৬ × ১০১৭ বছর',
      jet: '২.৯ × ১০১৪ বছর',
      voyager: '৪,৩০০ বছর'
    },
    domain: 'astrophysical',
    renderType: 'nebula',
    accentColor: '#f43f5e',
    summaryEn: 'A diffuse nebula situated in the Milky Way, 1,344 light years away. One of the brightest nebulae visible to the naked eye and an active stellar nursery.',
    summaryBn: '১৩৪৪ আলোকবর্ষ দূরে অবস্থিত একটি বিখ্যাত নক্ষত্র প্রসূতিগার। এখানে গ্যাস ও ধূলিকণার মহাকর্ষীয় সংকোচনে শত শত নতুন তারার জন্ম হচ্ছে।',
    factEn: 'The nebula contains protoplanetary disks (proplyds) which are nascent planetary systems forming in real-time.',
    factBn: 'এখানে প্রোটোপ্ল্যানেটারি ডিস্ক দৃশ্যমান—যেখানে নক্ষত্রদের চারপাশে নতুন সৌরজগতের জন্ম হচ্ছে বাস্তব সময়ে!',
    sources: 'NASA Hubble & JWST Surveys'
  },
  {
    order: 16.61,
    id: 'alpha_centauri_distance',
    nameEn: 'Alpha Centauri Distance',
    nameBn: 'আলফা সেন্টরাই নক্ষত্র দূরত্ব',
    sizeMeters: 4.1e16,
    sizeFormatted: '4.1 × 10¹⁶ m (~4.37 Light Years)',
    sizeFormattedBn: '৪.১ × ১০১৬ মিটার (~৪.৩৭ আলোকবর্ষ)',
    lightTime: '~4.37 Years',
    lightTimeBn: '~৪.৩৭ বছর',
    truthTag: 'measured',
    truthBadgeEn: 'Stellar Parallax Measured',
    truthBadgeBn: 'প্যারালাক্স পদ্ধতিতে পরিমাপকৃত',
    dominantForce: 'gravity',
    dominantForceEn: 'Interstellar Stellar Dynamics',
    dominantForceBn: 'আন্তঃনক্ষত্র মহাকর্ষ বল',
    instrumentEn: 'Stellar Astrometry & Parallax',
    instrumentBn: 'নাক্ষত্রিক প্যারালাক্স ও অ্যাস্ট্রোমেট্রি',
    humanTransit: {
      walk: '৯.৪ × ১০১৫ বছর',
      jet: '৫.২ × ১০১২ বছর',
      voyager: '৭৬,০০০ বছর'
    },
    domain: 'astrophysical',
    renderType: 'star_system',
    accentColor: '#fbbf24',
    summaryEn: 'The closest stellar system to the Solar System. A triple-star system consisting of Alpha Centauri A, B, and the red dwarf Proxima Centauri.',
    summaryBn: 'আমাদের সৌরজগতের সবচেয়ে নিকটবর্তী নক্ষত্রমণ্ডল। এটি তিনটি নক্ষত্রের জোট: আলফা সেন্টরাই এ, বি এবং প্রক্সিমা সেন্টরাই।',
    factEn: 'Even with mankind\'s fastest probe (Voyager 1 at 17 km/s), reaching Proxima Centauri would take over 75,000 years!',
    factBn: 'মানুষের তৈরি দ্রুততম মহাকাশযান ভয়েজার-১ নিয়ে রওনা হলেও প্রক্সিমা সেন্টরাইতে পৌঁছাতে ৭৫,০০০ বছর লাগবে!',
    sources: 'ESA Hipparcos / Gaia Catalog'
  },
  {
    order: 16.0,
    id: 'oort_cloud',
    nameEn: 'The Oort Cloud',
    nameBn: 'উর্ট মেঘ (Oort Cloud)',
    sizeMeters: 1.0e16,
    sizeFormatted: '1.0 × 10¹⁶ m (~1.06 Light Years)',
    sizeFormattedBn: '১.০ × ১০১৬ মিটার (~১.০৬ আলোকবর্ষ)',
    lightTime: '~1.06 Years',
    lightTimeBn: '~১.০৬ বছর',
    truthTag: 'speculative',
    truthBadgeEn: 'Inferred Cometary Reservoir',
    truthBadgeBn: 'অনুমান / ধূমকেতু উৎস তাত্ত্বিক',
    dominantForce: 'gravity',
    dominantForceEn: 'Weak Solar Gravity Influenced by Galactic Tides',
    dominantForceBn: 'দুর্বল সৌর মহাকর্ষ ও গ্যালাকটিক জোয়ার',
    instrumentEn: 'Long-period Comet Orbital Tracking',
    instrumentBn: 'দীর্ঘ পর্যায়কালের ধূমকেতুর কক্ষপথ মডেল',
    humanTransit: {
      walk: '২.৩ × ১০১৫ বছর',
      jet: '১.৩ × ১০১২ বছর',
      voyager: '১৯,০০০ বছর'
    },
    domain: 'astrophysical',
    renderType: 'oort_cloud',
    accentColor: '#93c5fd',
    summaryEn: 'A theoretical spherical cloud of predominantly icy planetesimals proposed to surround the Sun up to 100,000 AU. The source of long-period comets.',
    summaryBn: 'সৌরজগতের দূরতম সীমান্তে বরফ ও পাথুরে খণ্ডের একটি সুবিশাল গোলকাকার মেঘ। এটি সরাসরি দূরবীণে দেখা যায়নি, কিন্তু দীর্ঘ পর্যায়কালের ধূমকেতুর কক্ষপথ থেকে এর উপস্থিতি প্রমাণিত।',
    factEn: 'Voyager 1 will reach the inner edge of the Oort Cloud in about 300 years and take 30,000 years to pass through it.',
    factBn: 'ভয়েজার-১ আগামী ৩০০ বছরে উর্ট ক্লাউডের সীমানায় ঢুকবে এবং এটি পার হতে তার ৩০,০০০ বছর লাগবে!',
    sources: 'Jan Oort Hypothesis / IAU Working Group'
  },
  {
    order: 13.56,
    id: 'heliosphere',
    nameEn: 'The Heliosphere',
    nameBn: 'হেলিওস্ফিয়ার (সৌরচৌম্বক মণ্ডলী)',
    sizeMeters: 3.6e13,
    sizeFormatted: '3.6 × 10¹³ m (~240 AU)',
    sizeFormattedBn: '৩.৬ × ১০১৩ মিটার (~২৪০ এইউ)',
    lightTime: '~33.3 Hours',
    lightTimeBn: '~৩৩.৩ ঘণ্টা',
    truthTag: 'measured',
    truthBadgeEn: 'In-Situ Intersellar Boundary Mapped',
    truthBadgeBn: 'ভয়েজার মহাকাশযানে প্রত্যক্ষ পরিমাপকৃত',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Solar Wind Magnetic Bubble vs ISM',
    dominantForceBn: 'সৌর বায়ু ও চৌম্বক ক্ষেত্রের চাপ',
    instrumentEn: 'Voyager 1 & 2 Magnetometers',
    instrumentBn: 'ভয়েজার ১ ও ২ ম্যাগনেটোমিটার',
    humanTransit: {
      walk: '৮.২ × ১০১২ বছর',
      jet: '৪.৬ × ১০৯ বছর',
      voyager: '৬৭ বছর (১৯৭৭ সালে উৎক্ষেপণ)'
    },
    domain: 'planetary',
    renderType: 'heliosphere',
    accentColor: '#38bdf8',
    summaryEn: 'The vast bubble of space magnetized by the solar wind, shielding the planets from harmful cosmic radiation. Its boundary, the heliopause, marks the start of interstellar space.',
    summaryBn: 'সূর্যের সৌর বায়ু ও চৌম্বক ক্ষেত্র দ্বারা গঠিত একটি সুরক্ষামূলক বুদ্বুদ, যা গ্রহগুলোকে ক্ষতিকর গ্যালাকটিক কসমিক রশ্মি থেকে রক্ষা করে। এর শেষ প্রান্তকে হেলিওপজ বলে।',
    factEn: 'Voyager 1 crossed the heliopause in 2012, becoming humanity\'s first interstellar probe after 35 years of flight.',
    factBn: 'ভয়েজার-১ ২০১২ সালে হেলিওপজ পার হয়ে প্রথম মানবনির্মিত বস্তু হিসেবে আন্তঃনক্ষত্র মহাশূন্যে প্রবেশ করে!',
    sources: 'NASA Voyager Interstellar Mission Data'
  },
  {
    order: 13.18,
    id: 'kuiper_belt',
    nameEn: 'The Kuiper Belt',
    nameBn: 'কুইপার বেল্ট',
    sizeMeters: 1.5e13,
    sizeFormatted: '1.5 × 10¹³ m (~100 AU)',
    sizeFormattedBn: '১.৫ × ১০১৩ মিটার (~১০০ এইউ)',
    lightTime: '~13.9 Hours',
    lightTimeBn: '~১৩.৯ ঘণ্টা',
    truthTag: 'measured',
    truthBadgeEn: 'Trans-Neptunian Belt Mapped',
    truthBadgeBn: 'পরিমাপকৃত বরফবলয়',
    dominantForce: 'gravity',
    dominantForceEn: 'Solar Gravitational Field',
    dominantForceBn: 'সৌর মহাকর্ষ ও নেপচুনের রেজোন্যান্স',
    instrumentEn: 'Ground Telescopes & New Horizons Probe',
    instrumentBn: 'নিউ হরাইজন্স নভোযান ও গ্রাউন্ড টেলিস্কোপ',
    humanTransit: {
      walk: '৩.৪ × ১০১২ বছর',
      jet: '১.৯ × ১০৯ বছর',
      voyager: '২৮ বছর'
    },
    domain: 'planetary',
    renderType: 'kuiper_belt',
    accentColor: '#67e8f9',
    summaryEn: 'A circumstellar disc in the outer Solar System extending beyond the orbit of Neptune (30 to 50 AU). Home to dwarf planets like Pluto, Haumea, and Makemake.',
    summaryBn: 'নেপচুনের কক্ষপথের বাইরে অবস্থিত বরফ ও গ্রহাণু সমৃদ্ধ এক সুবিশাল ডিস্ক। প্লুটো, হাউমেয়া, মাকেমাকে ইত্যাদি বামন গ্রহ এখানে অবস্থান করে।',
    factEn: 'Light takes nearly 14 hours to travel across the diameter of the Kuiper Belt!',
    factBn: 'কুইপার বেল্টের পুরো ব্যাস পার হতে আলোর প্রায় ১৪ ঘণ্টা সময় লাগে!',
    sources: 'NASA New Horizons Mission / Minor Planet Center'
  },
  {
    order: 11.48,
    id: 'earth_orbit',
    nameEn: 'Earth\'s Orbit (2 AU)',
    nameBn: 'পৃথিবীর কক্ষপথের ব্যাস (২ AU)',
    sizeMeters: 3.0e11,
    sizeFormatted: '3.0 × 10¹¹ m (2 Astronomical Units)',
    sizeFormattedBn: '৩.০ × ১০১১ মিটার (২ অ্যাস্ট্রোনমিক্যাল ইউনিট)',
    lightTime: '~16.7 Minutes',
    lightTimeBn: '~১৬.৭ মিনিট',
    truthTag: 'measured',
    truthBadgeEn: 'Radar & Laser Astrometry',
    truthBadgeBn: 'রাডার ও লেজার রেঞ্জিং পরিমাপকৃত',
    dominantForce: 'gravity',
    dominantForceEn: 'Keplerian Solar Gravity',
    dominantForceBn: 'কেপলারীয় সৌর মহাকর্ষ বল',
    instrumentEn: 'Radar Telemetry & Orbital Dynamics',
    instrumentBn: 'রাডার টেলিমেট্রি ও কক্ষীয় বলবিদ্যা',
    humanTransit: {
      walk: '৬৮,৫০০ বছর',
      jet: '৩৮০ বছর',
      voyager: '২০৫ দিন'
    },
    domain: 'planetary',
    renderType: 'orbit_ring',
    accentColor: '#34d399',
    summaryEn: 'The path traversed by Earth around the Sun every 365.25 days. 1 AU is approximately 149.6 million kilometers.',
    summaryBn: 'সূর্যের চারদিকে পৃথিবীর পরিভ্রমণ কক্ষপথের পূর্ণ ব্যাস। সূর্যের আলো পৃথিবীর কক্ষপথের এক প্রান্ত থেকে অন্য প্রান্তে যেতে প্রায় ১৬.৭ মিনিট সময় নেয়।',
    factEn: 'Humanity uses the width of Earth\'s orbit as a cosmic baseline (parallax) to measure the distance to nearby stars.',
    factBn: 'পৃথিবীর কক্ষপথের এই ব্যাসকে জ্যোতির্বিজ্ঞানীরা মহাজাগতিক স্কেল হিসেবে ব্যবহার করে তারাদের দূরত্ব নির্ণয় করেন (প্যারালাক্স পদ্ধতি)!',
    sources: 'IAU Astronomical Constants 2012'
  },
  {
    order: 9.14,
    id: 'sun',
    nameEn: 'The Sun (Sol)',
    nameBn: 'সূর্য (আমাদের নক্ষত্র)',
    sizeMeters: 1.39e9,
    sizeFormatted: '1.39 × 10⁹ m (1.39 Million km)',
    sizeFormattedBn: '১.৩৯ × ১০৯ মিটার (১৩.৯ লক্ষ কিমি)',
    lightTime: '~4.64 Seconds',
    lightTimeBn: '~৪.৬৪ সেকেন্ড',
    truthTag: 'measured',
    truthBadgeEn: 'Helioseismology & Solar Dynamics',
    truthBadgeBn: 'হেলিওসিজমোলজি ও সোলার ডায়নামিক্সে পরিমাপকৃত',
    dominantForce: 'gravity',
    dominantForceEn: 'Hydrostatic Equilibrium (Gravity vs Fusion Pressure)',
    dominantForceBn: 'হাইড্রোস্ট্যাটিক ভারসাম্য (মহাকর্ষ বনাম ফিউশন চাপ)',
    instrumentEn: 'Solar & Heliospheric Observatory (SOHO / SDO)',
    instrumentBn: 'সোলার ডায়নামিক্স অবজারভেটরি (SDO)',
    blackHoleRadiusEn: 'If compressed into a black hole, the Sun\'s event horizon radius would be just 2.95 km (city size)!',
    blackHoleRadiusBn: 'সূর্যের মোট ভর (২ × ১০³⁰ কেজি) ব্ল্যাকহোলে পরিণত হলে এর ব্যাসার্ধ হবে মাত্র ২.৯৫ কিলোমিটার (একটি শহরের সমান)!',
    humanTransit: {
      walk: '৩১.৭ বছর',
      jet: '৬৪ দিন',
      voyager: '২২.৭ ঘণ্টা'
    },
    domain: 'planetary',
    renderType: 'sun_star',
    accentColor: '#f59e0b',
    summaryEn: 'A G-type main-sequence star comprising 99.86% of the Solar System\'s total mass. Its core fuses 600 million tons of hydrogen into helium every second.',
    summaryBn: 'একটি হলুদ বামন নক্ষত্র যা সমগ্র সৌরজগতের ৯৯.৮৬% ভর ধারণ করে। এর কেন্দ্রে প্রতি সেকেন্ডে ৬০ কোটি টন হাইড্রোজেন ফিউশন প্রক্রিয়ায় হিলিয়ামে রূপান্তরিত হচ্ছে।',
    factEn: 'A photon generated in the solar core takes 100,000 years to wander out to the surface, but only 8.3 minutes to reach Earth!',
    factBn: 'সূর্যের কোরে উৎপন্ন একটি ফোটন ধাক্কা খেতে খেতে পৃষ্ঠে উঠে আসতে ১ লক্ষ বছর লাগে, কিন্তু সেখান থেকে পৃথিবীতে পৌঁছাতে লাগে মাত্র ৮.৩ মিনিট!',
    sources: 'NASA SDO / CODATA Solar Radius'
  },
  {
    order: 8.16,
    id: 'jupiter',
    nameEn: 'Jupiter',
    nameBn: 'বৃহস্পতি গ্রহ',
    sizeMeters: 1.43e8,
    sizeFormatted: '1.43 × 10⁸ m (142,984 km)',
    sizeFormattedBn: '১.৪৩ × ১০৮ মিটার (১,৪২,৯৮৪ কিমি)',
    lightTime: '~0.48 Seconds',
    lightTimeBn: '~০.৪৮ সেকেন্ড',
    truthTag: 'measured',
    truthBadgeEn: 'In-Situ Spacecraft Mapping',
    truthBadgeBn: 'জুন্নো ও গ্যালিলিও নভোযানে পরিমাপকৃত',
    dominantForce: 'gravity',
    dominantForceEn: 'Planetary Gravitational Field',
    dominantForceBn: 'গ্রহীয় মহাকর্ষ ও শক্তিশালী চৌম্বক বল',
    instrumentEn: 'Juno Orbiter / Space Telescopes',
    instrumentBn: 'জুনো অরবিটার ও হাবল টেলিস্কোপ',
    blackHoleRadiusEn: 'If compressed into a black hole, Jupiter\'s event horizon would be just 2.82 meters (room size)!',
    blackHoleRadiusBn: 'বৃহস্পতির ভর ব্ল্যাকহোলে পরিণত হলে এর ব্যাসার্ধ হবে মাত্র ২.৮২ মিটার (একটি সাধারণ ঘরের সমান)!',
    humanTransit: {
      walk: '৩.৩ বছর',
      jet: '৬.৬ দিন',
      voyager: '২.৩ ঘণ্টা'
    },
    domain: 'planetary',
    renderType: 'jupiter_planet',
    accentColor: '#fb923c',
    summaryEn: 'The largest planet in the Solar System, more than twice as massive as all the other planets combined. Famous for its centuries-old Great Red Spot anticyclonic storm.',
    summaryBn: 'সৌরজগতের বৃহত্তম গ্রহ, যার ভর বাকি সব গ্রহের সম্মিলিত ভরের দ্বিগুণেরও বেশি। এর বুকে শতাব্দীর পর শতাব্দী ধরে চলছে গ্রেট রেড স্পট নামক দানবীয় ঘূর্ণিঝড়।',
    factEn: 'Jupiter\'s mass is so great that the center of gravity between it and the Sun lies outside the Sun\'s surface!',
    factBn: 'বৃহস্পতির ভর এত বেশি যে সূর্য ও বৃহস্পতির যৌথ ভরকেন্দ্র (Barycenter) সূর্যের পৃষ্ঠের বাইরে মহাশূন্যে অবস্থান করে!',
    sources: 'NASA Juno Mission Data'
  },
  {
    order: 7.10,
    id: 'earth',
    nameEn: 'Earth',
    nameBn: 'পৃথিবী (আমাদের নীলাভ গ্রহ)',
    sizeMeters: 1.27e7,
    sizeFormatted: '1.27 × 10⁷ m (12,742 km)',
    sizeFormattedBn: '১.২৭ × ১০৭ মিটার (১২,৭৪২ কিমি)',
    lightTime: '~0.042 Seconds (42.4 ms)',
    lightTimeBn: '~০.০৪২ সেকেন্ড (৪২.৪ মিলি-সেকেন্ড)',
    truthTag: 'measured',
    truthBadgeEn: 'Satellite Geodesy Measured',
    truthBadgeBn: 'স্যাটেলাইট জিওডেসি দ্বারা নিখুঁত পরিমাপকৃত',
    dominantForce: 'gravity',
    dominantForceEn: 'Planetary Gravity & Magnetic Dynamo',
    dominantForceBn: 'গ্রহীয় মহাকর্ষ ও কোর ডায়নামো',
        instrumentEn: 'GRACE Satellites / GPS Geodesy',
    instrumentBn: 'স্যাটেলাইট জিওডেসি ও জিপিএস নেটওয়ার্ক',
    blackHoleRadiusEn: 'Compressing Earth into a black hole requires crushing it into a tiny sphere of just 8.87 mm (marble/penny size)!',
    blackHoleRadiusBn: 'পুরো পৃথিবীকে ব্ল্যাকহোল বানাতে হলে তাকে সংকুচিত করে মাত্র ৮.৮৭ মিলিমিটার (একটি মার্বেল বা মুদ্রার আকার)-এ আনতে হবে!',
    humanTransit: {
      walk: '৩৩৪ দিন (না থেমে হাঁটলে)',
      jet: '১৪ ঘণ্টা (ব্যাস বরাবর)',
      voyager: '১২.৫ মিনিট'
    },
    domain: 'planetary',
    renderType: 'earth_globe',
    accentColor: '#38bdf8',
    summaryEn: 'Our home world and the only known harbor of life in the universe. An active terrestrial world with a dynamic liquid water ocean surface and protective magnetosphere.',
    summaryBn: 'মহাবিশ্বে প্রাণের অস্তিত্বের একমাত্র জ্ঞাত আবাসভূমি। তরল পানির মহাসাগর, টেকটোনিক প্লেট এবং চৌম্বক বলয়ের সুরক্ষায় আবৃত এক অনন্য নীলাভ জগৎ।',
    factEn: 'Light can circle the Earth\'s equator 7.5 times in just one second!',
    factBn: 'আলো মাত্র এক সেকেন্ডে পুরো পৃথিবীর বিষুবরেখা ৭.৫ বার প্রদক্ষিণ করতে পারে!',
    sources: 'WGS-84 Geodetic Datum / NASA'
  },
  {
    order: 3.95,
    id: 'mount_everest',
    nameEn: 'Mount Everest',
    nameBn: 'মাউন্ট এভারেস্ট',
    sizeMeters: 8848,
    sizeFormatted: '8,848 m (8.85 km Height)',
    sizeFormattedBn: '৮,৮৪৮ মিটার (৮.৮৫ কিমি উচ্চতা)',
    lightTime: '~29.5 Microseconds (μs)',
    lightTimeBn: '~২৯.৫ মাইক্রোসেকেন্ড (μs)',
    truthTag: 'measured',
    truthBadgeEn: 'Laser Rangefinding & GPS Survey',
    truthBadgeBn: 'লেজার রেঞ্জফাইন্ডিং ও জিপিএস জরিপ',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Electromagnetic Solid Rock Strength vs Gravity',
    dominantForceBn: 'পাথরের আন্তঃআণবিক বন্ধন বনাম মহাকর্ষ',
    instrumentEn: 'LiDAR / GPS Geodetic Stations',
    instrumentBn: 'লাইডার ও জিপিএস জিওডেটিক স্টেশন',
    blackHoleRadiusEn: 'Compressing Mount Everest yields an event horizon of just 1.2 picometers (smaller than an atom)!',
    blackHoleRadiusBn: 'পুরো এভারেস্ট পর্বতকে ব্ল্যাকহোলে পরিণত করলে এর ব্যাসার্ধ হবে মাত্র ১.২ পিকোমিটার (একটিমাত্র পরমাণুর চেয়েও ছোট)!',
    humanTransit: {
      walk: '১.৭ ঘণ্টা (সমতল গতিতে)',
      jet: '৩৫ সেকেন্ড',
      voyager: '০.৫২ সেকেন্ড'
    },
    domain: 'macro',
    renderType: 'mountain',
    accentColor: '#94a3b8',
    summaryEn: 'Earth\'s highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas. Formed by the tectonic collision of India and Eurasia.',
    summaryBn: 'সমুদ্রপৃষ্ঠ থেকে পৃথিবীর সর্বোচ্চ পর্বতশৃঙ্গ। ভারতীয় ও ইউরেশীয় প্লেটের মহাদেশীয় সংঘর্ষের ফলে হিমালয়ের এই শৃঙ্গটি আজও প্রতি বছর প্রায় ৪ মিমি উঁচু হচ্ছে।',
    factEn: 'At the summit, atmospheric pressure is just 33% of sea level, meaning the human body starves of oxygen within minutes without adaptation.',
    factBn: 'এভারেস্টের চূড়ায় বাতাসের চাপ সমতলের মাত্র এক-তৃতীয়াংশ, ফলে পর্যাপ্ত অভিযোজন ছাড়া মানবদেহ কয়েক মিনিটে চেতনা হারায়!',
    sources: 'Survey of Nepal & China 2020'
  },
  {
    order: 3.79,
    id: 'padma_bridge',
    nameEn: 'Padma Multipurpose Bridge',
    nameBn: 'পদ্মা বহুমুখী সেতু',
    sizeMeters: 6150,
    sizeFormatted: '6,150 m (6.15 km Length)',
    sizeFormattedBn: '৬,১৫০ মিটার (৬.১৫ কিমি দৈর্ঘ্য)',
    lightTime: '~20.5 Microseconds (μs)',
    lightTimeBn: '~২০.৫ মাইক্রোসেকেন্ড (μs)',
    truthTag: 'measured',
    truthBadgeEn: 'Civil Engineering Metrology',
    truthBadgeBn: 'পরিমাপকৃত মেগা-স্থাপত্য',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Structural Steel & Pre-stressed Concrete',
    dominantForceBn: 'ইস্পাত ও কংক্রিটের তাড়িতচৌম্বক বন্ধন',
    instrumentEn: 'Laser Total Station / GNSS Surveying',
    instrumentBn: 'লেজার টোটাল স্টেশন ও জিএনএসএস জরিপ',
    humanTransit: {
      walk: '১.২ ঘণ্টা (না থেমে হাঁটলে)',
      jet: '২৪.৬ সেকেন্ড',
      voyager: '০.৩৬ সেকেন্ড'
    },
    domain: 'macro',
    renderType: 'padma_bridge',
    accentColor: '#38bdf8',
    summaryEn: 'A landmark engineering marvel of Bangladesh crossing the turbulent Padma River. Spans 6.15 kilometers with 41 steel truss spans resting on deep friction piles.',
    summaryBn: 'বাংলাদেশের খরস্রোতা পদ্মা নদীর বুকে নির্মিত ৬.১৫ কিলোমিটার দীর্ঘ দ্বি-তল ইস্পাত ট্রাস মেগা-সেতু। এর পাইলগুলো পৃথিবীর যেকোনো সেতুর চেয়ে সবচেয়ে গভীরে (১২২ মিটার) প্রোথিত।',
    factEn: 'The friction steel piles of Padma Bridge plunge 122 meters deep into the riverbed—a world record in civil bridge foundations!',
    factBn: 'পদ্মা সেতুর স্টিল পাইলগুলো নদীর তলদেশের ১২২ মিটার গভীরে প্রবেশ করানো হয়েছে—যা বিশ্ব রেকর্ড!',
    sources: 'Padma Bridge Project Directorate / BBA'
  },
  {
    order: 0.23,
    id: 'human',
    nameEn: 'Human Being',
    nameBn: 'মানুষ (মানব স্কেল)',
    sizeMeters: 1.7,
    sizeFormatted: '1.7 m (Typical Adult Height)',
    sizeFormattedBn: '১.৭ মিটার (গড় প্রাপ্তবয়স্ক উচ্চতা)',
    lightTime: '~5.67 Nanoseconds (ns)',
    lightTimeBn: '~৫.৬৭ ন্যানোসেকেন্ড (ns)',
    truthTag: 'measured',
    truthBadgeEn: 'Direct Metric Measurement',
    truthBadgeBn: 'সরাসরি ফিতা ও অপটিক্যাল পরিমাপ',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Chemical Bonds (Cellular Structures)',
    dominantForceBn: 'কোষীয় রাসায়নিক বন্ধন (তাড়িতচৌম্বক বল)',
    instrumentEn: 'Naked Eye / Standard Metric Ruler',
    instrumentBn: 'খালি চোখ ও পরিমাপক ফিতা',
    blackHoleRadiusEn: 'A 70 kg human would need to be crushed into 1.04 × 10⁻²⁵ meters (approaching Planck domain)!',
    blackHoleRadiusBn: '৭০ কেজি ওজনের একজন মানুষকে ব্ল্যাকহোলে পরিণত করতে হলে তাকে ১.০৪ × ১০⁻²৫ মিটারে (প্ল্যাঙ্ক স্কেলের কাছাকাছি) সংকুচিত করতে হবে!',
    humanTransit: {
      walk: '১.২ সেকেন্ড',
      jet: '৬.৮ মিলি-সেকেন্ড',
      voyager: '০.১ মিলি-সেকেন্ড'
    },
    domain: 'macro',
    renderType: 'human_figure',
    accentColor: '#10b981',
    summaryEn: 'An anatomically modern Homo sapiens composed of approximately 37 trillion cells and 7 × 10²⁷ atoms. Standing at the exact geometric midpoint between the observable universe and the Planck length!',
    summaryBn: 'প্রায় ৩৭ ট্রিলিয়ন জীবকোষ ও ৭ × ১০২৭ টি পরমাণুর এক সচেতন জটিল জীব। জ্যামিতিক স্কেলের বিচারে মানুষ অবস্থান করছে দৃশ্যমান মহাবিশ্ব এবং প্ল্যাঙ্ক দৈর্ঘ্যের ঠিক মাঝখানে!',
    factEn: 'If your body was scaled up to the size of Earth, an individual cell would be the size of a five-story building!',
    factBn: 'আপনার দেহকে যদি পৃথিবীর সমান বড় করা হতো, তবে আপনার একটিমাত্র কোষ হতো পাঁচতলা ভবনের সমান!',
    sources: 'WHO Anthropometric Reference / Bianconi et al.'
  },
  {
    order: -1.82,
    id: 'honeybee',
    nameEn: 'Western Honey Bee',
    nameBn: 'মৌমাছি',
    sizeMeters: 0.015,
    sizeFormatted: '1.5 cm (15 mm)',
    sizeFormattedBn: '১.৫ সেমি (১৫ মিমি)',
    lightTime: '~50 Picoseconds (ps)',
    lightTimeBn: '~৫০ পিকোসেকেন্ড (ps)',
    truthTag: 'measured',
    truthBadgeEn: 'Macro Photography Verified',
    truthBadgeBn: 'ম্যাক্রো লেন্স ও ভার্নিয়ার ক্যালিপার্স',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Biological Chitin Structural Bonds',
    dominantForceBn: 'কাইটিন জৈব রাসায়নিক বন্ধন',
    instrumentEn: 'Optical Macro Lens / Magnifier',
    instrumentBn: 'ম্যাক্রো লেন্স ও সাধারণ আতশ কাচ',
    humanTransit: {
      walk: '১০.৮ মিলি-সেকেন্ড',
      jet: '৬০ মাইক্রোসেকেন্ড',
      voyager: '০.৮৮ মাইক্রোসেকেন্ড'
    },
    domain: 'macro',
    renderType: 'insect',
    accentColor: '#facc15',
    summaryEn: 'A eusocial flying insect known for honey construction and pollination. Has a brain containing just 1 million neurons yet capable of complex symbolic dance communication.',
    summaryBn: 'পরাগায়নের প্রধান কারিগর এই পতঙ্গের মস্তিষ্কে মাত্র ১০ লক্ষ নিউরন রয়েছে, তবুও তারা জটিল সংকেতবাহী "ওয়াগল ডান্স"-এর মাধ্যমে ফুলের সন্ধান আদান-প্রদান করতে পারে।',
    factEn: 'A honey bee flaps its wings 230 times per second, creating an electrostatic charge that attracts pollen through electric fields!',
    factBn: 'মৌমাছি প্রতি সেকেন্ডে ২৩০ বার ডানা ঝাপটায়, যার ফলে তাদের শরীরে স্থির বিদ্যুৎ তৈরি হয়ে ফুলের রেণুকে চুম্বকের মতো টেনে নেয়!',
    sources: 'Biological Insect Anatomy Compendium'
  },
  {
    order: -3.30,
    id: 'grain_of_sand',
    nameEn: 'Grain of Beach Sand',
    nameBn: 'বালুকণা (সমুদ্র সৈকত)',
    sizeMeters: 5.0e-4,
    sizeFormatted: '0.5 mm (500 μm)',
    sizeFormattedBn: '০.৫ মিমি (৫০০ মাইক্রন)',
    lightTime: '~1.67 Picoseconds (ps)',
    lightTimeBn: '~১.৬৭ পিকোসেকেন্ড (ps)',
    truthTag: 'measured',
    truthBadgeEn: 'Optical Micrometer Measured',
    truthBadgeBn: 'অপটিক্যাল মাইক্রোমিটার পরিমাপকৃত',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Silicon Dioxide (SiO2) Crystal Lattice',
    dominantForceBn: 'সিলিকন ডাই-অক্সাইড স্ফটিক বন্ধন',
    instrumentEn: 'Optical Stereo Microscope',
    instrumentBn: 'স্টেরিও মাইক্রোস্কোপ',
    humanTransit: {
      walk: '০.৩৬ মিলি-সেকেন্ড',
      jet: '২.০ মাইক্রোসেকেন্ড',
      voyager: '২৯ ন্যানোসেকেন্ড'
    },
    domain: 'macro',
    renderType: 'sand_grain',
    accentColor: '#fde047',
    summaryEn: 'A fine mineral particle typically composed of eroded silicon dioxide (quartz). Represents the perceptual threshold of the naked human eye.',
    summaryBn: 'সিলিকন ডাই-অক্সাইডের ক্ষয়প্রাপ্ত স্ফটিক। এটি মানুষের খালি চোখে কোনো লেন্স ছাড়া স্পষ্টভাবে দেখতে পাওয়ার সর্বনিম্ন সীমার কাছাকাছি।',
    factEn: 'There are approximately 7.5 × 10¹⁸ grains of sand on all of Earth\'s beaches—vastly fewer than the number of stars in the observable universe (10²²)!',
    factBn: 'পৃথিবীর সব সমুদ্র সৈকতে যত বালুকণা রয়েছে (৭.৫ × ১০১৮), দৃশ্যমান মহাবিশ্বে নক্ষত্রের সংখ্যা (১০২২) তার চেয়ে বহুগুণ বেশি!',
    sources: 'Wentworth Grain Size Scale'
  },
  {
    order: -3.52,
    id: 'dust_mite',
    nameEn: 'Dust Mite (Dermatophagoides)',
    nameBn: 'ধুলো-মাইট (Dust Mite)',
    sizeMeters: 3.0e-4,
    sizeFormatted: '0.3 mm (300 μm)',
    sizeFormattedBn: '০.৩ মিমি (৩০০ মাইক্রন)',
    lightTime: '~1.0 Picosecond (ps)',
    lightTimeBn: '~১.০ পিকোসেকেন্ড (ps)',
    truthTag: 'measured',
    truthBadgeEn: 'Stereo Microscope Verified',
    truthBadgeBn: 'স্টেরিও অণুবীক্ষণ যন্ত্রে পরিমাপকৃত',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Cellular & Chitin Integrity',
    dominantForceBn: 'জৈব কাইটিন বন্ধন',
    instrumentEn: 'Optical Microscope (40x)',
    instrumentBn: 'অপটিক্যাল অণুবীক্ষণ যন্ত্র (৪০x)',
    humanTransit: {
      walk: '০.২১ মিলি-সেকেন্ড',
      jet: '১.২ মাইক্রোসেকেন্ড',
      voyager: '১৭ ন্যানোসেকেন্ড'
    },
    domain: 'micro',
    renderType: 'dust_mite',
    accentColor: '#e2e8f0',
    summaryEn: 'A microscopic arachnid that lives in human habitats and feeds on dead skin flakes. Barely discernable to the naked eye against dark backgrounds.',
    summaryBn: 'মানুষের ঝরে পড়া মৃত চামড়া খেয়ে বেঁচে থাকা এক আণুবীক্ষণিক অ্যারাকনিড কীট। এটি মানুষের একটি চুলের চেয়ে বড় হলেও খালি চোখে দেখা প্রায় অসম্ভব।',
    factEn: 'Dust mites do not drink water; they absorb atmospheric moisture directly through glands on the sides of their bodies.',
    factBn: 'ধুলো-মাইট কখনো পানি পান করে না; তারা শরীরের পাশের বিশেষ গ্রন্থি দিয়ে সরাসরি বাতাসের আর্দ্রতা শুষে নেয়!',
    sources: 'Arthropod Morphology Database'
  },
  {
    order: -4.10,
    id: 'human_hair',
    nameEn: 'Human Hair Thickness',
    nameBn: 'মানুষের চুলের পুরুত্ব',
    sizeMeters: 8.0e-5,
    sizeFormatted: '80 μm (0.08 mm)',
    sizeFormattedBn: '৮০ মাইক্রন (০.০৮ মিমি)',
    lightTime: '~0.27 Picoseconds (ps)',
    lightTimeBn: '~০.২৭ পিকোসেকেন্ড (ps)',
    truthTag: 'measured',
    truthBadgeEn: 'Laser Micrometer Measured',
    truthBadgeBn: 'লেজার মাইক্রোমিটারে পরিমাপকৃত',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Keratin Protein Crosslinks (Disulfide Bonds)',
    dominantForceBn: 'কেরাটিন প্রোটিনের ডাইসালফাইড বন্ধন',
    instrumentEn: 'Optical Microscope & Caliper',
    instrumentBn: 'অপটিক্যাল মাইক্রোস্কোপ ও ক্যালিপার',
    humanTransit: {
      walk: '৫৮ মাইক্রোসেকেন্ড',
      jet: '০.৩ মাইক্রোসেকেন্ড',
      voyager: '৪.৭ ন্যানোসেকেন্ড'
    },
    domain: 'micro',
    renderType: 'hair_fiber',
    accentColor: '#ca8a04',
    summaryEn: 'A filamentous biomaterial composed of dense keratin protein. Widely used as a familiar everyday reference for microscopic dimensions.',
    summaryBn: 'কেরাটিন প্রোটিনের শক্ত ফিলামেন্ট। আণুবীক্ষণিক মাত্রার বস্তুকে বোঝাতে মানুষের চুলকে বিশ্বজুড়ে রেফারেন্স হিসেবে ব্যবহার করা হয়।',
    factEn: 'A single strand of hair can support up to 100 grams in weight without snapping thanks to dense disulfide chemical bonds.',
    factBn: 'ডাইসালফাইড রাসায়নিক বন্ধনের দৃঢ়তার কারণে একটিমাত্র মাথার চুল না ছিঁড়ে ১০০ গ্রাম ওজন ঝুলিয়ে রাখতে পারে!',
    sources: 'Forensic Fiber Analysis Handbook'
  },
  {
        order: -5.12,
    id: 'red_blood_cell',
    nameEn: 'Red Blood Cell (Erythrocyte)',
    nameBn: 'লোহিত রক্তকণিকা (Erythrocyte)',
    sizeMeters: 7.5e-6,
    sizeFormatted: '7.5 μm (7,500 nm)',
    sizeFormattedBn: '৭.৫ মাইক্রন (৭,৫০০ ন্যানোমিটার)',
    lightTime: '~25 Femtoseconds (fs)',
    lightTimeBn: '~২৫ ফেমটোসেকেন্ড (fs)',
    truthTag: 'measured',
    truthBadgeEn: 'Brightfield Optical Microscopy',
    truthBadgeBn: 'অপটিক্যাল ব্রাইটফিল্ড অণুবীক্ষণ যন্ত্রে পরিমাপকৃত',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Lipid Bilayer & Hemoglobin Conformation',
    dominantForceBn: 'লিপিড বাইলেয়ার ও হিমোগ্লোবিন রূপ',
    instrumentEn: 'High-Power Optical Microscope (1000x)',
    instrumentBn: 'উচ্চক্ষমতাসম্পন্ন অপটিক্যাল অণুবীক্ষণ যন্ত্র (১০০০x)',
    humanTransit: {
      walk: '৫.৪ মাইক্রোসেকেন্ড',
      jet: '৩০ ন্যানোসেকেন্ড',
      voyager: '০.৪৪ ন্যানোসেকেন্ড'
    },
    domain: 'micro',
    renderType: 'rbc_cell',
    accentColor: '#ef4444',
    summaryEn: 'The most common type of blood cell delivering oxygen through cardiovascular networks. Has a biconcave disc shape to maximize gas exchange surface area.',
    summaryBn: 'মানবদেহের ফুসফুস থেকে কোষে কোষে অক্সিজেন পরিবহনকারী দ্বি-অবতল চাকতি আকৃতির কোষ। গ্যাসীয় আদান-প্রদান বাড়াতে এটি তার নিউক্লিয়াস ত্যাগ করে।',
    factEn: 'Your body produces about 2.4 million new red blood cells every single second to replace aging ones!',
    factBn: 'প্রতি সেকেন্ডে আপনার শরীরে প্রায় ২৪ লক্ষ নতুন লোহিত রক্তকণিকা তৈরি হয় পুরোনো কণিকা প্রতিস্থাপন করতে!',
    sources: 'Medical Physiology Guyton & Hall'
  },
  {
    order: -5.70,
    id: 'bacterium_ecoli',
    nameEn: 'Bacterium (Escherichia coli)',
    nameBn: 'ব্যাকটেরিয়া (ই. কোলাই)',
    sizeMeters: 2.0e-6,
    sizeFormatted: '2.0 μm (2,000 nm)',
    sizeFormattedBn: '২.০ মাইক্রন (২,০০০ ন্যানোমিটার)',
    lightTime: '~6.67 Femtoseconds (fs)',
    lightTimeBn: '~৬.৬৭ ফেমটোসেকেন্ড (fs)',
    truthTag: 'measured',
    truthBadgeEn: 'Phase Contrast Optical Microscopy',
    truthBadgeBn: 'ফেজ কনট্রাস্ট অণুবীক্ষণ যন্ত্রে পরিমাপকৃত',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Peptidoglycan Cell Wall Matrix',
    dominantForceBn: 'পেপটিডোগ্লাইকান কোষপ্রাচীর বন্ধন',
    instrumentEn: 'Phase Contrast / Fluorescence Microscope',
    instrumentBn: 'ফেজ কনট্রাস্ট ও ফ্লুরোসেন্স মাইক্রোস্কোপ',
    humanTransit: {
      walk: '১.৪৪ মাইক্রোসেকেন্ড',
      jet: '৮.০ ন্যানোসেকেন্ড',
      voyager: '০.১২ ন্যানোসেকেন্ড'
    },
    domain: 'micro',
    renderType: 'bacteria',
    accentColor: '#10b981',
    summaryEn: 'A rod-shaped gram-negative bacterium found in the digestive tract of warm-blooded organisms. A foundational model organism in molecular genetics.',
    summaryBn: 'রড আকৃতির একটি এককোষী অণুজীব। মানবদেহের অন্ত্রে বসবাসকারী এই ব্যাকটেরিয়াটি আধুনিক জেনেটিক্স ও আণবিক জীববিজ্ঞানের প্রধান গবেষণাগার জীব।',
    factEn: 'E. coli propels itself with rotary flagella engines driven by a proton pump that spins at up to 1,000 RPM!',
    factBn: 'ই. কোলাই ব্যাক্টেরিয়া ফ্ল্যাজেলার রোটরি মোটর ব্যবহার করে সাঁতার কাটে, যা প্রতি মিনিটে ১,০০০ বার পর্যন্ত ঘুরতে পারে!',
    sources: 'Brock Biology of Microorganisms'
  },
  {
    order: -7.0,
    id: 'virus_t4',
    nameEn: 'T4 Bacteriophage Virus',
    nameBn: 'টি৪ ব্যাকটেরিওফায ভাইরাস',
    sizeMeters: 1.0e-7,
    sizeFormatted: '100 nm (0.1 μm)',
    sizeFormattedBn: '১০০ ন্যানোমিটার (০.১ মাইক্রন)',
    lightTime: '~0.33 Femtoseconds (fs)',
    lightTimeBn: '~০.৩৩ ফেমটোসেকেন্ড (fs)',
    truthTag: 'model',
    truthBadgeEn: 'False-Color Electron Micrograph',
    truthBadgeBn: 'মডেল / ক্রায়ো-ইলেক্ট্রন ফলস-কালার',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Protein Capsid Geometry & Van der Waals',
    dominantForceBn: 'ভ্যান ডার ওয়ালস ও ক্যাপসিড বন্ধন',
    instrumentEn: 'Scanning / Transmission Electron Microscope (SEM)',
    instrumentBn: 'ট্রান্সমিশন ইলেকট্রন অণুবীক্ষণ যন্ত্র (TEM)',
    humanTransit: {
      walk: '৭২ ন্যানোসেকেন্ড',
      jet: '০.৪ ন্যানোসেকেন্ড',
      voyager: '৫.৯ পিকোসেকেন্ড'
    },
    domain: 'nano',
    renderType: 'virus_capsid',
    accentColor: '#a855f7',
    summaryEn: 'A virus that infects and replicates within bacteria. Resembles a lunar lander with an icosahedral head packaging DNA and tail fibers that anchor to cell walls.',
    summaryBn: 'ব্যাকটেরিয়া শিকারী এক রোবটতুল্য ভাইরাস। এর বিশতলকীয় প্রোটিন মাথার ভেতরে প্যাকেট করা ডিএনএ থাকে এবং এটি স্প্রিং ইঞ্জিনের মতো ব্যাকটেরিয়ার শরীরে ডিএনএ ইনজেক্ট করে।',
    factEn: 'Because viruses are smaller than 400 nm (the wavelength of violet light), they possess no natural color. Any colored image of a virus is purely artificial false-color!',
    factBn: 'ভাইরাস দৃশ্যমান আলোর ক্ষুদ্রতম তরঙ্গের (৪০০ ন্যানোমিটার) চেয়েও ছোট হওয়ায় তাদের নিজস্ব কোনো রং নেই। ভাইরাসের রঙিন সব ছবিই কম্পিউটারের কাল্পনিক রং!',
    sources: 'Cryo-EM Structural Database (PDB)'
  },
  {
    order: -8.30,
    id: 'protein_hemoglobin',
    nameEn: 'Hemoglobin Protein',
    nameBn: 'হিমোগ্লোবিন প্রোটিন',
    sizeMeters: 5.0e-9,
    sizeFormatted: '5.0 nm (50 Å)',
    sizeFormattedBn: '৫.০ ন্যানোমিটার (৫০ অ্যাংস্ট্রম)',
    lightTime: '~16.7 Attoseconds (as)',
    lightTimeBn: '~১৬.৭ অ্যাটোসেকেন্ড (as)',
    truthTag: 'model',
    truthBadgeEn: 'X-Ray Crystallography Model',
    truthBadgeBn: 'মডেল / এক্স-রে ক্রিস্টালোগ্রাফি কাঠামো',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Peptide Bonds & Hydrogen Bond Folding',
    dominantForceBn: 'পেপটাইড ও হাইড্রোজেন বন্ধন রূপ',
    instrumentEn: 'X-Ray Crystallography / Cryo-EM',
    instrumentBn: 'এক্স-রে ক্রিস্টালোগ্রাফি ও ক্রায়ো-ইএম',
    humanTransit: {
      walk: '৩.৬ ন্যানোসেকেন্ড',
      jet: '২০ পিকোসেকেন্ড',
      voyager: '০.২৯ পিকোসেকেন্ড'
    },
    domain: 'nano',
    renderType: 'protein_folding',
    accentColor: '#ec4899',
    summaryEn: 'The iron-containing oxygen-transport metalloprotein in red blood cells. A tetrameric protein that changes physical shape (allostery) when binding oxygen.',
    summaryBn: 'রক্তের লোহিত কণিকায় থাকা আয়রনযুক্ত প্রোটিন যন্ত্র। এটিতে চারটি সাবইউনিট থাকে যা ফুসফুসে অক্সিজেন গ্রহণ করার সাথে সাথে যান্ত্রিকভাবে নিজের আকার পরিবর্তন করে।',
    factEn: 'A single red blood cell contains approximately 270 million hemoglobin molecules!',
    factBn: 'একটিমাত্র লোহিত রক্তকণিকায় প্রায় ২৭ কোটি হিমোগ্লোবিন অণু ঠাসা অবস্থায় থাকে!',
    sources: 'RCSB Protein Data Bank (PDB ID: 1A3N)'
  },
  {
    order: -8.70,
    id: 'dna_helix',
    nameEn: 'DNA Double Helix',
    nameBn: 'ডিএনএ ডাবল হেলিক্স',
    sizeMeters: 2.0e-9,
    sizeFormatted: '2.0 nm (20 Å Width)',
    sizeFormattedBn: '২.০ ন্যানোমিটার (২০ অ্যাংস্ট্রম প্রস্থ)',
    lightTime: '~6.67 Attoseconds (as)',
    lightTimeBn: '~৬.৬৭ অ্যাটোসেকেন্ড (as)',
    truthTag: 'model',
    truthBadgeEn: 'Atomic Model / Photo 51 Verified',
    truthBadgeBn: 'মডেল / এক্স-রে অপবর্তন প্রতিরূপ',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Hydrogen Bonds between Base Pairs (A-T, C-G)',
    dominantForceBn: 'ক্ষারক জোড়ের হাইড্রোজেন বন্ধন',
    instrumentEn: 'X-Ray Diffraction / Atomic Force Microscope (AFM)',
    instrumentBn: 'এক্স-রে ডিফ্র্যাকশন ও পারমাণবিক বল অণুবীক্ষণ যন্ত্র',
    humanTransit: {
      walk: '১.৪৪ ন্যানোসেকেন্ড',
      jet: '৮.০ পিকোসেকেন্ড',
      voyager: '০.১২ পিকোসেকেন্ড'
    },
    domain: 'nano',
    renderType: 'dna_helix',
    accentColor: '#06b6d4',
    summaryEn: 'The molecular blueprint of all terrestrial life. A polymer composed of four nucleotide bases arranged in a right-handed twisted ladder held by hydrogen bonds.',
    summaryBn: 'পৃথিবীর সমস্ত প্রাণের বংশগতির আণবিক ব্লুপ্রিন্ট। অ্যাডেনিন, থাইমিন, গুয়ানিন ও সাইটোসিন ক্ষারকের হাইড্রোজেন বন্ধনে গঠিত এক অবিস্মরণীয় প্যাঁচানো সিঁড়ি।',
    factEn: 'If the DNA in a single human cell were uncoiled and stretched end-to-end, it would be 2 meters long, yet fits inside a 6-micron nucleus!',
    factBn: 'আপনার একটিমাত্র কোষের ডিএনএ-কে সোজা করলে তা ২ মিটার লম্বা হবে, অথচ তা মাত্র ৬ মাইক্রন চওড়া নিউক্লিয়াসে নিখুঁতভাবে ভাঁজ হয়ে থাকে!',
    sources: 'Watson & Crick 1953 / PDB Data'
  },
  {
    order: -10.0,
    id: 'hydrogen_atom',
    nameEn: 'Hydrogen Atom',
    nameBn: 'হাইড্রোজেন পরমাণু (কোয়ান্টাম ক্লাউড)',
    sizeMeters: 1.0e-10,
    sizeFormatted: '1.0 Å (0.1 nm / 10⁻¹⁰ m)',
    sizeFormattedBn: '১.০ অ্যাংস্ট্রম (০.১ ন্যানোমিটার)',
    lightTime: '~0.33 Attoseconds (as)',
    lightTimeBn: '~০.৩৩ অ্যাটোসেকেন্ড (as)',
    truthTag: 'model',
    truthBadgeEn: 'Measured Size (0.53 Å) | Quantum Cloud |ψ|²',
    truthBadgeBn: 'পরিমাপকৃত আকার (০.৫৩ Å) | কোয়ান্টাম সম্ভাবনা মেঘ |ψ|²',
    dominantForce: 'electromagnetism',
    dominantForceEn: 'Coulomb Electrostatic Attraction',
    dominantForceBn: 'কুলম্বের স্থির তাড়িতচৌম্বক আকর্ষণ',
    instrumentEn: 'Scanning Tunneling Microscope (STM) / Spectroscopy',
    instrumentBn: 'স্ক্যানিং টানেলিং মাইক্রোস্কোপ (STM) ও বর্ণালীবীক্ষণ',
    humanTransit: {
      walk: '৭২ পিকোসেকেন্ড',
      jet: '০.৪ পিকোসেকেন্ড',
      voyager: '৫.৯ ফেমটোসেকেন্ড'
    },
    misconception: {
      titleBn: 'বোর মডেলের গ্রহীয় কক্ষপথ সম্পূর্ণ ভুল!',
      realityBn: 'পরমাণু কোনো খুদে সৌরজগৎ নয় যেখানে ইলেকট্রন বলের মতো নির্দিষ্ট পথে ঘোরে। ইলেকট্রন হলো কোয়ান্টাম তরঙ্গ ফাংশন—এটি একই সাথে পরমাণুর সর্বত্র সম্ভাব্যতার মেঘ আকারে বিরাজ করে।'
    },
    domain: 'nano',
    renderType: 'hydrogen_cloud',
    accentColor: '#38bdf8',
    summaryEn: 'The simplest and most abundant element in the universe. Consists of a single proton nucleus bound to an electron quantum probability cloud defined by the Schrödinger wave equation.',
    summaryBn: 'মহাবিশ্বের সবচেয়ে সরল ও প্রাচুর্যময় মৌল। একটিমাত্র প্রোটন এবং শ্রোডিঙ্গার সমীকরণ দ্বারা সংজ্ঞায়িত ইলেকট্রনের কোয়ান্টাম সম্ভাবনা মেঘ (|ψ|²) নিয়ে এটি গঠিত।',
    factEn: 'If an atom were expanded to the size of a giant 100-meter football stadium, the central nucleus would be no larger than a grain of rice or pinhead (~1 mm) in the center, and the rest is vacuum!',
    factBn: 'একটি পরমাণুকে যদি ১০০ মিটারের সুবিশাল ফুটবল স্টেডিয়াম ভাবা হয়, তবে এর কেন্দ্রস্থ নিউক্লিয়াসটি হবে মাঠের মাঝে রাখা ছোট একটি চালের দানা বা আলপিনের মাথার সমান (~১ মিলিমিটার), আর বাকি ৯৯.৯৯৯% স্থানই সম্পূর্ণ শূন্যতা!',
    sources: 'CODATA Bohr Radius (0.529 Å) / Quantum Mechanics'
  },
  {
    order: -14.0,
    id: 'atomic_nucleus',
    nameEn: 'Atomic Nucleus (Carbon-12)',
    nameBn: 'পারমাণবিক নিউক্লিয়াস (কার্বন-১২)',
    sizeMeters: 5.4e-15,
    sizeFormatted: '5.4 fm (5.4 × 10⁻¹⁵ m)',
    sizeFormattedBn: '৫.৪ ফেমটোমিটার (৫.৪ × ১০⁻১৫ মিটার)',
    lightTime: '~18.0 Yoctoseconds (ys)',
    lightTimeBn: '~১৮.০ ইওক্টোসেকেন্ড (ys)',
    truthTag: 'model',
    truthBadgeEn: 'Nuclear Scattering Model',
    truthBadgeBn: 'মডেল / কণা বিচ্ছুরণ নিউক্লিয়ার মডেল',
    dominantForce: 'strong',
    dominantForceEn: 'Residual Strong Nuclear Force (Yukawa Interaction)',
    dominantForceBn: 'অবশিষ্ট সবল নিউক্লীয় বল (পায়নের আদান-প্রদান)',
    instrumentEn: 'High-Energy Electron Scattering (SLAC)',
    instrumentBn: 'উচ্চশক্তির ইলেকট্রন বিচ্ছুরণ (SLAC)',
    humanTransit: {
      walk: '৩.৯ ফেমটোসেকেন্ড',
      jet: '২১ অ্যাটোসেকেন্ড',
      voyager: '০.৩১ অ্যাটোসেকেন্ড'
    },
    domain: 'nuclear',
    renderType: 'atomic_nucleus',
    accentColor: '#f43f5e',
    summaryEn: 'The dense core of an atom containing protons and neutrons bound tightly by the residual strong nuclear force, overcoming intense electrostatic proton repulsion.',
    summaryBn: 'পরমাণুর ৯৯.৯% ভর ধারণকারী কেন্দ্র। প্রোটনদের মধ্যকার তীব্র স্থির তড়িৎ বিকর্ষণ বলকে পরাস্ত করে মেসন/পায়নের শক্তিশালী নিউক্লীয় বল এদের একসঙ্গে বেঁধে রাখে।',
    factEn: 'Nuclear matter is unimaginably dense: 2.3 × 10¹⁷ kg/m³. One teaspoon of pure nuclear material would weigh over 1 billion tons!',
    factBn: 'নিউক্লিয়াসের ঘনত্ব অবর্ণনীয়: ২.৩ × ১০১৭ কেজি/ঘনমিটার। এক চা-চামচ বিশুদ্ধ নিউক্লিয়ার পদার্থের ওজন হবে ১০০ কোটি টনেরও বেশি!',
    sources: 'Charge Radii of Nuclei / Hofstadter Electron Scattering'
  },
  {
    order: -14.77,
    id: 'proton',
    nameEn: 'Proton (Nucleon)',
    nameBn: 'প্রোটন (সবল বলের ইঞ্জিন)',
    sizeMeters: 1.7e-15,
    sizeFormatted: '1.7 fm (1.7 × 10⁻¹⁵ m Diameter)',
    sizeFormattedBn: '১.৭ ফেমটোমিটার (১.৭ × ১০⁻১৫ মিটার)',
    lightTime: '~5.67 Yoctoseconds (ys)',
    lightTimeBn: '~৫.৬৭ ইওক্টোসেকেন্ড (ys)',
    truthTag: 'measured',
    truthBadgeEn: 'Charge Radius Directly Measured',
    truthBadgeBn: 'পরিমাপকৃত চার্জ ব্যাসার্ধ (০.৮৪১ fm)',
    dominantForce: 'strong',
    dominantForceEn: 'Quantum Chromodynamics (Gluon Color Force)',
    dominantForceBn: 'কোয়ান্টাম ক্রোমোডায়নামিক্স (গ্লুয়ন কালার বল)',
    instrumentEn: 'Muonic Hydrogen Spectroscopy / High-Energy Colliders',
    instrumentBn: 'মিউওনিক হাইড্রোজেন স্পেকট্রোস্কোপি ও কণা ত্বরক',
    humanTransit: {
      walk: '১.২২ ফেমটোসেকেন্ড',
      jet: '৬.৮ অ্যাটোসেকেন্ড',
      voyager: '০.১ অ্যাটোসেকেন্ড'
    },
    misconception: {
      titleBn: 'প্রোটনের ভর কোয়ার্ক থেকে আসে না!',
      realityBn: 'প্রোটনের তিনটি ভ্যালেন্স কোয়ার্কের (uud) সম্মিলিত ভর প্রোটনের মোট ভরের মাত্র ১%! বাকি ৯৯% ভর আসে তাদের আবদ্ধ রাখা গ্লুয়ন ক্ষেত্রের গতিশক্তি ও বাইন্ডিং এনার্জি থেকে (E = mc²)।'
    },
    domain: 'nuclear',
    renderType: 'proton_quarks',
    accentColor: '#fb7185',
    summaryEn: 'A stable subatomic hadron composed of two Up quarks and one Down quark bound by a turbulent sea of gluons and virtual quark-antiquark pairs.',
    summaryBn: 'মহাবিশ্বের পদার্থের স্থায়ী স্তম্ভ। দুটি আপ কোয়ার্ক ও একটি ডাউন কোয়ার্ক দিয়ে গঠিত হলেও এর আসল সত্তা হলো আলোর গতিতে ঘূর্ণায়মান গ্লুয়ন বলক্ষেত্রের এক ফুটন্ত সমুদ্র।',
    factEn: 'Free protons are virtually immortal. Particle physics experiments set their minimum half-life at greater than 10³⁴ years—far longer than the age of the universe!',
    factBn: 'মুক্ত প্রোটন প্রায় অমর। গবেষণায় দেখা গেছে একটি প্রোটনের আয়ুষ্কাল কমপক্ষে ১০৩৪ বছর—যা বর্তমান মহাবিশ্বের বয়সের চেয়েও কোটি কোটি গুণ বেশি!',
    sources: 'Particle Data Group (PDG 2022) / CODATA Proton Radius'
  },
  {
    order: -18.0,
    id: 'quark_electron_limit',
    nameEn: 'Quark & Electron Upper Bound',
    nameBn: 'কোয়ার্ক ও ইলেকট্রন উর্ধ্বসীমা',
    sizeMeters: 1.0e-18,
    sizeFormatted: '< 10⁻¹⁸ m (Point-Like Limit)',
    sizeFormattedBn: '< ১০⁻১৮ মিটার (বিন্দুবৎ কণার সীমা)',
    lightTime: '3.33 × 10⁻²⁷ s (0.0033 ys)',
    lightTimeBn: '৩.৩৩ × ১০⁻২৭ সেকেন্ড (০.০০৩৩ ys)',
    truthTag: 'measured',
    truthBadgeEn: 'Experimental Upper Limit (Point-Like)',
    truthBadgeBn: 'পরীক্ষালব্ধ উর্ধ্বসীমা (বিন্দুবৎ কণা)',
    dominantForce: 'strong',
    dominantForceEn: 'Fundamental Gauge Couplings',
    dominantForceBn: 'মৌলিক গেজ কাপলিং বল',
    instrumentEn: 'Deep Inelastic Scattering (HERA / SLAC)',
    instrumentBn: 'ডিপ ইনইলাস্টিক স্ক্যাটারিং (HERA / SLAC)',
    humanTransit: {
      walk: '৭.২ × ১০⁻১৯ সেকেন্ড',
      jet: '৪.০ × ১০⁻২১ সেকেন্ড',
      voyager: '৫.৯ × ১০⁻২৩ সেকেন্ড'
    },
    misconception: {
      titleBn: 'কোয়ার্ক বা ইলেকট্রনের কোনো আকার নেই!',
      realityBn: 'কোয়ার্ক ও ইলেকট্রন কোনো ছোট বল বা গোলক নয়। স্ট্যান্ডার্ড মডেল অনুসারে এগুলো শূন্য-আয়তনের বিন্দুবৎ (Point-like) কণা। ১০⁻১৮ মিটার হলো আমাদের বর্তমান ডিটেক্টরের পরিমাপের উর্ধ্বসীমা মাত্র।'
    },
    domain: 'nuclear',
    renderType: 'fundamental_point',
    accentColor: '#38bdf8',
    summaryEn: 'Fundamental elementary particles with no known internal substructure. In the Standard Model they are mathematical points; 10⁻¹⁸ m is merely the upper experimental resolution limit.',
    summaryBn: 'পদার্থের মৌলিক অবিভাজ্য একক। আধুনিক স্ট্যান্ডার্ড মডেল অনুসারে এদের কোনো অভ্যন্তরীণ কাঠামো বা আয়তন নেই; এরা নিখুঁত জ্যামিতিক বিন্দুবৎ কণা।',
    factEn: 'If an electron has an actual physical radius, it must be smaller than 10⁻²² meters according to high-precision Penning trap measurements!',
    factBn: 'পেনিং ট্র্যাপ ল্যাবরেটরি পরীক্ষায় দেখা গেছে যদি ইলেকট্রনের কোনো বাস্তব ব্যাসার্ধ থেকেও থাকে, তা ১০⁻২২ মিটারের চেয়েও ক্ষুদ্র!',
    sources: 'Particle Data Group (PDG) / High Energy Physics'
  },
  {
    order: -18.5,
    id: 'electroweak_scale',
    nameEn: 'Electroweak Symmetry Breaking & Higgs Field',
    nameBn: 'ইলেকট্রোউইক স্কেল ও হিগস ক্ষেত্র',
    sizeMeters: 3.16e-19,
    sizeFormatted: '~3.2 × 10⁻¹⁹ m (~250 GeV)',
    sizeFormattedBn: '~৩.২ × ১০⁻১৯ মিটার (~২৫০ GeV)',
    lightTime: '1.05 × 10⁻²⁷ s',
    lightTimeBn: '১.০৫ × ১০⁻২৭ সেকেন্ড',
    truthTag: 'measured',
    truthBadgeEn: 'Higgs Mechanism Verified',
    truthBadgeBn: 'পরিমাপকৃত হিগস মেকানিজম সীমা',
    dominantForce: 'weak',
    dominantForceEn: 'Electroweak Unification (W/Z Bosons)',
    dominantForceBn: 'ইলেকট্রোউইক বল ও হিগস ফিল্ড ইন্টারঅ্যাকশন',
    instrumentEn: 'Large Hadron Collider (CERN ATLAS & CMS)',
    instrumentBn: 'লার্জ হ্যাড্রন কলাইডার (CERN - ATLAS ও CMS)',
    humanTransit: {
      walk: '২.৩ × ১০⁻১৯ সেকেন্ড',
      jet: '১.৩ × ১০⁻২১ সেকেন্ড',
      voyager: '১.৯ × ১০⁻২৩ সেকেন্ড'
    },
    domain: 'nuclear',
    renderType: 'higgs_field',
    accentColor: '#fbbf24',
    summaryEn: 'The energy scale where the electromagnetic and weak forces unify into a single electroweak force. Particles acquire mass through interactions with the pervasive Higgs vacuum field.',
    summaryBn: 'যে স্কেলে বিদ্যুৎচৌম্বক বল এবং দুর্বল নিউক্লীয় বল একত্রিত হয়ে একটি অবিভাজ্য একক বলে রূপ নেয়। এই স্কেলেই হিগস বোসন কণা অন্যান্য কণিকাকে ভর প্রদান করে।',
    factEn: 'Discovered in 2012 at CERN, the Higgs boson was the final missing piece predicted by the Standard Model of particle physics.',
    factBn: '২০১২ সালে সার্নে আবিষ্কৃত হিগস বোসন কণা প্রমাণ করে যে স্থান-কাল শূন্য নয়, বরং এক অদৃশ্য হিগস ক্ষেত্রে পূর্ণ যা মৌলিক কণাদের ভর উপহার দেয়!',
    sources: 'CERN ATLAS & CMS Collaborations 2012'
  },
  {
    order: -19.0,
    id: 'lhc_probing_limit',
    nameEn: 'LHC Probing Limit',
    nameBn: 'এলএইচসি প্রযুক্তির সর্বনিম্ন সীমা',
    sizeMeters: 1.0e-19,
    sizeFormatted: '1.0 × 10⁻¹⁹ m (0.1 Atto-meter)',
    sizeFormattedBn: '১.০ × ১০⁻১৯ মিটার (০.১ অ্যাটোমিটার)',
    lightTime: '3.33 × 10⁻²⁸ s',
    lightTimeBn: '৩.৩৩ × ১০⁻২৮ সেকেন্ড',
    truthTag: 'measured',
    truthBadgeEn: 'Deepest Technological Probe',
    truthBadgeBn: 'মানবজাতির গভীরতম পর্যবেক্ষণ প্রযুক্তি',
    dominantForce: 'weak',
    dominantForceEn: '13.6 TeV Collision Debris',
    dominantForceBn: '১৩.৬ TeV শক্তি-ভর রূপান্তর',
    instrumentEn: 'Large Hadron Collider (27 km Superconducting Ring)',
    instrumentBn: 'সার্নের লার্জ হ্যাড্রন কলাইডার (২৭ কিমি বলয়)',
    humanTransit: {
      walk: '৭.২ × ১০⁻২০ সেকেন্ড',
      jet: '৪.০ × ১০⁻২২ সেকেন্ড',
      voyager: '৫.৯ × ১০⁻২৪ সেকেন্ড'
    },
    domain: 'planck',
    renderType: 'lhc_limit',
    accentColor: '#ef4444',
    summaryEn: 'The smallest physical distance scale directly probed by human instrumentation. At 13.6 TeV, protons collide with enough localized energy to resolve features down to a fraction of an attometer.',
    summaryBn: 'মানবজাতির প্রযুক্তির ইতিহাসের সবচেয়ে ক্ষুদ্রতম পরিমাপ সীমা। আলোর ৯৯.৯৯৯৯৯৯১% গতিতে প্রোটনের মুখোমুখি সংঘর্ষ ঘটিয়ে বিজ্ঞানীরা স্থান-কালের ১০⁻১৯ মিটার গভীরতা পর্যন্ত নিরীক্ষা করেছেন।',
    factEn: 'At this extreme scale, technology reaches its pinnacle. For comparison, the LIGO gravitational wave detector sensed arm-length variations of ~4 × 10⁻¹⁸ m during GW150914—less than a thousandth of a proton width!',
    factBn: 'এই অতিক্ষুদ্র স্কেলে প্রযুক্তি তার চূড়ান্ত সীমায় পৌঁছায়। তুলনামূলকভাবে, লাইগো (LIGO) মহাকর্ষীয় তরঙ্গ শনাক্ত করতে ইন্টারফেরোমিটারের বাহুর মাত্র ~৪ × ১০⁻১৮ মিটার সূক্ষ্ম পরিবর্তন পরিমাপ করে—যা প্রোটনের ব্যাসের হাজার ভাগের এক ভাগ!',
    sources: 'CERN Experimental Reports / Particle Data Group'
  },
  {
    order: -27.0,
    id: 'neutrino_seesaw_scale',
    nameEn: 'Neutrino Seesaw Scale (The Desert)',
    nameBn: 'নিউট্রিনো সি-স স্কেল (তাত্ত্বিক মরুভূমি)',
    sizeMeters: 2.0e-27,
    sizeFormatted: '~2.0 × 10⁻²⁷ m (Energy Equiv: ~10¹¹ GeV)',
    sizeFormattedBn: '~২.০ × ১০⁻২৭ মিটার (শক্তির সমতুল্য: ~১০¹¹ GeV)',
    lightTime: '6.67 × 10⁻³⁶ s',
    lightTimeBn: '৬.৬৭ × ১০⁻৩৬ সেকেন্ড',
    truthTag: 'theoretical',
    truthBadgeEn: 'Theoretical Probing Scale (λ = ħc/E)',
    truthBadgeBn: 'তাত্ত্বিক / শক্তির সমতুল্য দৈর্ঘ্য (λ = ħc/E)',
    dominantForce: 'weak',
    dominantForceEn: 'Majorana Mass Mechanism (Heavy Sterile Neutrinos)',
    dominantForceBn: 'মায়োরানা ভর মেকানিজম (ভারী স্টেরাইল নিউট্রিনো)',
    instrumentEn: 'Pure Mathematical Physics (λ = ħc/E Equivalence)',
    instrumentBn: 'বিশুদ্ধ গাণিতিক পদার্থবিজ্ঞান (λ = ħc/E সমতুল্য)',
    humanTransit: {
      walk: '১.৪ × ১০⁻২৭ সেকেন্ড',
      jet: '৮.০ × ১০⁻৩০ সেকেন্ড',
      voyager: '১.২ × ১০⁻৩১ সেকেন্ড'
    },
    domain: 'planck',
    renderType: 'physics_desert',
    accentColor: '#9333ea',
    summaryEn: 'Welcome to the Great Particle Physics Desert. This does not represent a physical rigid object, but rather the spatial probing distance corresponding to ~10¹¹ GeV (λ = ħc/E). Between the LHC and GUT scales, the standard model predicts no new particles, only sterile neutrino masses.',
    summaryBn: 'কণা পদার্থবিজ্ঞানের মহাশূন্য মরুভূমি। এটি কোনো কঠিন বস্তুর আকার নয়; বরং প্রায় ১০¹¹ GeV শক্তিতে স্থান-কালের যে গভীরতা নিরীক্ষা করা সম্ভব (de Broglie দৈর্ঘ্য λ = ħc/E)। নিউট্রিনোর অতি-ক্ষুদ্র ভর ব্যাখ্যা করতে সি-স মেকানিজম এই স্কেলের প্রস্তাব করে।',
    factEn: 'Why are neutrinos so light? The seesaw mechanism posits ultra-heavy partner neutrinos exist at this energy scale, depressing standard neutrino masses!',
    factBn: 'নিউট্রিনো কণা কেন এত অবিশ্বাস্য রকমের হালকা? সি-স থিওরি অনুসারে এই অতিক্ষুদ্র শক্তিস্কেলে এক অতিভারী প্রতিরূপ নিউট্রিনো সাধারণ নিউট্রিনোর ভর কমিয়ে দেয়!',
    sources: 'Minkowski Seesaw Mechanism / Theoretical Particle Physics'
  },
  {
    order: -31.7,
    id: 'cosmic_inflation_scale',
    nameEn: 'Cosmic Inflation Epoch',
    nameBn: 'মহাজাগতিক স্ফীতি যুগ (Cosmic Inflation)',
    sizeMeters: 2.0e-32,
    sizeFormatted: '~2.0 × 10⁻³২ m (Energy Equiv: ~10¹⁶ GeV Horizon)',
    sizeFormattedBn: '~২.০ × ১০⁻৩২ মিটার (১০¹৬ GeV স্ফীতি দিগন্ত)',
    lightTime: '6.67 × 10⁻⁴১ s',
    lightTimeBn: '৬.৬৭ × ১০⁻৪১ সেকেন্ড',
    truthTag: 'theoretical',
    truthBadgeEn: 'Early Universe Horizon (λ = ħc/E)',
    truthBadgeBn: 'তাত্ত্বিক স্ফীতি দিগন্ত (λ = ħc/E)',
    dominantForce: 'quantum-gravity',
    dominantForceEn: 'Inflaton Scalar Field Potential',
    dominantForceBn: 'ইনফ্ল্যাটন স্কেলার ক্ষেত্রীয় শক্তি',
    instrumentEn: 'Cosmic Microwave Background B-mode Polarization Models',
    instrumentBn: 'সিএমবি বি-মোড পোলারাইজেশন তাত্ত্বিক মডেল',
    humanTransit: {
      walk: '১.৪ × ১০⁻৩২ সেকেন্ড',
      jet: '৮.০ × ১০⁻৩৫ সেকেন্ড',
      voyager: '১.২ × ১০⁻৩৬ সেকেন্ড'
    },
    domain: 'planck',
    renderType: 'inflation_field',
    accentColor: '#c084fc',
    summaryEn: 'The characteristic Hubble horizon scale during the Inflationary epoch (10⁻³⁶ s after the Big Bang) at ~10¹⁶ GeV (λ = ħc/E ≈ 2×10⁻³² m), when spacetime expanded exponentially, seeding galaxies across the universe.',
    summaryBn: 'মহাজাগতিক স্ফীতি যুগের (Cosmic Inflation) শক্তিমত্তা ~১০¹⁶ GeV, যার সমতুল্য তরঙ্গদৈর্ঘ্য প্রায় ২ × ১০⁻³২ মিটার (λ = ħc/E)। বিগ ব্যাং-এর প্রথম ১০⁻৩৬ সেকেন্ডে মহাবিশ্ব যখন অতিদ্রুত প্রসারিত হয়, তখনকার কোয়ান্টাম ফ্লাকচুয়েশনের দিগন্ত সীমা।',
    factEn: 'Quantum fluctuations at this microscopic energy scale were blown up to cosmological sizes, becoming the galaxy clusters we observe today!',
    factBn: 'এই ক্ষুদ্র স্কেলের কোয়ান্টাম কাঁপুনিই স্ফীতির কারণে প্রসারিত হয়ে আজকের বিশাল বিশাল গ্যালাক্সি ক্লাস্টারে রূপ নিয়েছে!',
    sources: 'Guth & Linde Inflation Models / BICEP/Keck Array'
  },
  {
    order: -32.0,
    id: 'gut_scale',
    nameEn: 'Grand Unified Theory (GUT) Scale',
    nameBn: 'গ্র্যান্ড ইউনিফাইড থিওরি (GUT) স্কেল',
    sizeMeters: 1.0e-32,
    sizeFormatted: '~1.0 × 10⁻³২ m (~10¹⁶ GeV)',
    sizeFormattedBn: '~১.০ × ১০⁻৩২ মিটার (~১০১৬ GeV)',
    lightTime: '3.33 × 10⁻⁴¹ s',
    lightTimeBn: '৩.৩৩ × ১০⁻৪১ সেকেন্ড',
    truthTag: 'theoretical',
    truthBadgeEn: 'Hypothetical Force Unification',
    truthBadgeBn: 'তাত্ত্বিক মৌলিক বলের মহাকেন্দ্র',
    dominantForce: 'strong',
    dominantForceEn: 'Unified Gauge Force (Strong + Electroweak)',
    dominantForceBn: 'একীভূত গেজ বল (সবল + তাড়িতচৌম্বক + দুর্বল)',
    instrumentEn: 'Theoretical Physics (Proton Decay Detectors like Super-K)',
    instrumentBn: 'সুপার-কামিওকান্দে প্রোটন ক্ষয় অনুসন্ধান',
    humanTransit: {
      walk: '৭.২ × ১০⁻৩৩ সেকেন্ড',
      jet: '৪.০ × ১০⁻৩৫ সেকেন্ড',
      voyager: '৫.৯ × ১০⁻৩৭ সেকেন্ড'
    },
    domain: 'planck',
    renderType: 'gut_unification',
    accentColor: '#e879f9',
    summaryEn: 'The theoretical scale where the strong, weak, and electromagnetic fundamental forces merge into one singular grand force. The energy required is 1 trillion times beyond the LHC.',
    summaryBn: 'যে চরম স্কেলে প্রকৃতির সবল, দুর্বল এবং তড়িৎচৌম্বক বল একত্রিত হয়ে একটি সর্বজনীন মহাপরাক্রমশালী শক্তিতে রূপ নেয়। এই স্কেল প্রত্যক্ষ করার মতো কণা ত্বরক বানানো মানুষের পক্ষে অসম্ভব।',
    factEn: 'At the GUT scale, matter and antimatter become interchangeable, which may explain why our universe is made of matter and not nothingness!',
    factBn: 'এই স্কেলে পদার্থ ও প্রতি-পদার্থের মধ্যে রূপান্তর ঘটে, যা ব্যাখ্যা করে কেন মহাবিশ্বে শূন্যতার বদলে পদার্থের সৃষ্টি হয়েছিল!',
    sources: 'Georgi-Glashow SU(5) Model / Super-Kamiokande'
  },
  {
    order: -34.0,
    id: 'quantum_foam',
    nameEn: 'Quantum Foam & Spacetime Fluctuations',
    nameBn: 'কোয়ান্টাম ফোম ও স্থান-কালের ফেনা',
    sizeMeters: 1.0e-34,
    sizeFormatted: '~1.0 × 10⁻³⁴ m',
    sizeFormattedBn: '~১.০ × ১০⁻৩৪ মিটার',
    lightTime: '3.33 × 10⁻⁴³ s',
    lightTimeBn: '৩.৩৩ × ১০⁻৪৩ সেকেন্ড',
    truthTag: 'speculative',
    truthBadgeEn: 'Speculative Quantum Gravity Concept',
    truthBadgeBn: 'অনুমান / অপ্রমাণিত কোয়ান্টাম ফোম',
    dominantForce: 'quantum-gravity',
    dominantForceEn: 'Spacetime Metric Quantum Fluctuations',
    dominantForceBn: 'স্থান-কালের মেট্রিক কোয়ান্টাম ফ্ল্যাকচুয়েশন',
    instrumentEn: 'None (Beyond Any Known Instrument)',
    instrumentBn: 'কোনো যন্ত্র নেই (বিজ্ঞানের শেষ ফ্রন্টিয়ার)',
    humanTransit: {
      walk: '৭.২ × ১০⁻৩৫ সেকেন্ড',
      jet: '৪.০ × ১০⁻৩৭ সেকেন্ড',
      voyager: '৫.৯ × ১০⁻৩৯ সেকেন্ড'
    },
    domain: 'planck',
    renderType: 'quantum_foam',
    accentColor: '#d946ef',
    summaryEn: 'Hypothesized by John Wheeler in 1955: at this extreme scale, smooth space and time dissolve into a turbulent, boiling froth of quantum topological wormholes and micro-singularities.',
    summaryBn: '১৯৫৫ সালে জন হুইলারের প্রস্তাবিত কোয়ান্টাম ফোম: এই চরম গভীরতায় আইনস্টাইনের মসৃণ স্থান-কাল ভেঙে চুরমার হয়ে যায় এবং স্থান নিজেই ফুটন্ত ফেনার মতো কোয়ান্টাম অস্থিরতায় মেতে ওঠে।',
    factEn: 'Because space itself fluctuates here, the concepts of "here", "there", "before", and "after" lose their geometric meaning!',
    factBn: 'এখানে স্থান নিজেই টগবগ করে ফুটতে থাকায় "আগে", "পরে", "এখানে" বা "ওখানে"-র মতো জ্যামিতিক ধারণাই অর্থহীন হয়ে পড়ে!',
    sources: 'John Wheeler Geometrodynamics / Hawking Micro-wormholes'
  },
  {
    order: -34.79,
    id: 'planck_length',
    nameEn: 'Planck Length & The Fundamental Limit',
    nameBn: 'প্ল্যাঙ্ক দৈর্ঘ্য ও পরম ভৌত সীমা',
    sizeMeters: 1.616e-35,
    sizeFormatted: '1.616 × 10⁻³⁵ m (The Indivisible Limit)',
    sizeFormattedBn: '১.৬১৬ × ১০⁻৩৫ মিটার (প্রকৃতির অবিভাজ্য সীমা)',
    lightTime: '5.39 × 10⁻⁴⁴ s (Planck Time tp)',
    lightTimeBn: '৫.৩৯ × ১০⁻৪৪ সেকেন্ড (প্ল্যাঙ্ক সময় tp)',
    truthTag: 'theoretical',
    truthBadgeEn: 'Ultimate Limit of Current Physics',
    truthBadgeBn: 'বর্তমান পদার্থবিজ্ঞানের পরম সীমা',
    dominantForce: 'quantum-gravity',
    dominantForceEn: 'Quantum Gravity (String Theory / Loop QG)',
    dominantForceBn: 'কোয়ান্টাম মহাকর্ষ ও স্ট্রিং ভাইব্রেশন',
    instrumentEn: 'Mathematical Formula ℓ_P = √(ħG/c³)',
    instrumentBn: 'গাণিতিক সূত্র ℓ_P = √(ħG/c³)',
    humanTransit: {
      walk: '১.১৬ × ১০⁻৩৫ সেকেন্ড',
      jet: '৬.৫ × ১০⁻৩৮ সেকেন্ড',
      voyager: '৯.৫ × ১০⁻৪০ সেকেন্ড'
    },
    misconception: {
      titleBn: 'প্ল্যাঙ্ক দৈর্ঘ্য কোনো প্রমাণিত স্ক্রিন পিক্সেল নয়!',
      realityBn: 'জনপ্রিয় ভুল ধারণা হলো মহাবিশ্ব নাকি প্ল্যাঙ্ক দৈর্ঘ্যের পিক্সেলে তৈরি। বাস্তবে বিজ্ঞান এটি প্রমাণ করেনি; এটি এমন এক দৈর্ঘ্য যেখানে মহাকর্ষ ও কোয়ান্টাম মেকানিক্স একসাথে ধাক্কা খায় এবং স্থান-কাল ব্ল্যাকহোলে পরিণত হয়।'
    },
    domain: 'planck',
    renderType: 'planck_limit',
    accentColor: '#f43f5e',
    summaryEn: 'Derived by Max Planck from fundamental constants: ℓ_P = √(ħG/c³). Below this scale, probing requires so much energy that a microscopic black hole forms, preventing smaller measurement. String theory posits 1D strings vibrate here.',
    summaryBn: 'মহাবিশ্বের পরম ক্ষুদ্রতম তাত্ত্বিক সীমা: ℓ_P = √(ħG/c³)। এর চেয়ে ক্ষুদ্র কোনো দূরত্ব দেখতে চাইলে ফোটনের শক্তি এত বেশি হবে যে তা সাথে সাথে ক্ষুদ্র ব্ল্যাকহোল তৈরি করে সব ঢেকে দেবে। স্ট্রিং থিওরি অনুসারে এখানে ১-মাত্রিক স্ট্রিং কম্পিত হয়ে শক্তি সৃষ্টি করে।',
    factEn: 'A grain of sand is as much larger than the Planck length as the entire observable universe is larger than that grain of sand!',
    factBn: 'একটি বালুকণা দৃশ্যমান মহাবিশ্বের তুলনায় যত ক্ষুদ্র, প্ল্যাঙ্ক দৈর্ঘ্য সেই একটি বালুকণার তুলনায় ঠিক ততটাই ক্ষুদ্র!',
    sources: 'Max Planck 1899 / Quantum Gravitational Limits'
  }
];

// Helper functions for dataset lookup and milestone navigation
export function getObjectByOrder(order) {
  let closest = COSMIC_OBJECTS[0];
  let minDiff = Math.abs(order - closest.order);
  for (const obj of COSMIC_OBJECTS) {
    const diff = Math.abs(order - obj.order);
    if (diff < minDiff) {
      minDiff = diff;
      closest = obj;
    }
  }
  return closest;
}

export function getDomainForOrder(order) {
  for (const d of SCALE_DOMAINS) {
    if (order >= d.min && order <= d.max) {
      return d;
    }
  }
  return SCALE_DOMAINS[SCALE_DOMAINS.length - 1];
}

export const SCALE_COMPARISONS = [
  {
    targetA: 'observable_universe',
    targetB: 'grain_of_sand',
    ratio: '1.76 × 10³⁰',
    ratioBn: '১.৭৬ × ১০³⁰',
    descEn: 'The entire observable universe is 10³⁰ times larger than a grain of beach sand.',
    descBn: 'দৃশ্যমান মহাবিশ্ব একটি সাধারণ সমুদ্র সৈকতের বালুকণার তুলনায় প্রায় ১০³⁰ গুণ বিশাল।'
  },
  {
    targetA: 'grain_of_sand',
    targetB: 'planck_length',
    ratio: '3.09 × 10³¹',
    ratioBn: '৩.০৯ × ১০³১',
    descEn: 'A single grain of sand is as much larger than the Planck length as the observable universe is larger than that grain of sand!',
    descBn: 'একটি বালুকণা প্ল্যাঙ্ক দৈর্ঘ্যের তুলনায় ঠিক ততটাই বড়, যতটা দৃশ্যমান মহাবিশ্ব সেই বালুকণাটির চেয়ে বড়!'
  },
  {
    targetA: 'human',
    targetB: 'red_blood_cell',
    ratio: '2.26 × 10⁵',
    ratioBn: '২.২৬ × ১০⁵',
    descEn: 'Approximately 226,000 red blood cells stacked end-to-end match the height of an adult human.',
    descBn: 'একটি পূর্ণবয়স্ক মানুষের উচ্চতায় প্রায় ২ লক্ষ ২৬ হাজার লোহিত রক্তকণিকা পাশাপাশি এঁটে যাবে।'
  },
  {
    targetA: 'hydrogen_atom',
    targetB: 'atomic_nucleus',
    ratio: '1.85 × 10⁴',
    ratioBn: '১.৮৫ × ১০⁴',
    descEn: 'The hydrogen atom electron cloud is nearly 20,000 times wider than its central nucleus (100 m football stadium vs 1 mm grain of rice).',
    descBn: 'হাইড্রোজেন পরমাণুর ইলেকট্রন মেঘ তার নিউক্লিয়াসের চেয়ে প্রায় ২০,০০০ গুণ চওড়া (১০০ মিটারের স্টেডিয়াম বনাম ১ মিলিমিটারের চালের দানা)।'
  },
  {
    targetA: 'proton',
    targetB: 'planck_length',
    ratio: '1.05 × 10²⁰',
    ratioBn: '১.০৫ × ১০²⁰',
    descEn: 'Across the diameter of a single proton, exactly 10²⁰ Planck lengths would fit end-to-end.',
    descBn: 'একটিমাত্র প্রোটনের ব্যাস জুড়ে সারিবদ্ধভাবে ১০²⁰টি প্ল্যাঙ্ক দৈর্ঘ্য এঁটে যাবে।'
  },
  {
    targetA: 'milky_way',
    targetB: 'earth_orbit',
    ratio: '3.17 × 10⁹',
    ratioBn: '৩.১৭ × ১০৯',
    descEn: 'The Milky Way galaxy is over 3 billion times wider than Earth\'s entire orbit around the Sun.',
    descBn: 'আমাদের আকাশগঙ্গা গ্যালাক্সি সূর্যের চারদিকে পৃথিবীর কক্ষপথের পূর্ণ ব্যাসের চেয়েও ৩০০ কোটি গুণ চওড়া!'
  }
];

export const SCALE_QUIZ_QUESTIONS = [
  {
    questionBn: 'ডিএনএ (DNA) ডাবল হেলিক্সের প্রস্থ আনুমানিক কত?',
    questionEn: 'What is the approximate diameter of a DNA double helix?',
    options: ['২ ন্যানোমিটার (2 nm)', '২ মাইক্রন (2 µm)', '২ মিলিমিটার (2 mm)', '০.২ অ্যাংস্ট্রম (0.2 Å)'],
    correctIndex: 0,
    explanationBn: 'ডিএনএ ডাবল হেলিক্সের ব্যাস প্রায় ২ ন্যানোমিটার (১০⁻⁸.⁷ মিটার)।',
    targetOrder: -8.7
  },
  {
    questionBn: 'একটি সাধারণ মানব লোহিত রক্তকণিকার (RBC) ব্যাস কত?',
    questionEn: 'What is the diameter of a human red blood cell?',
    options: ['৭.৫ মাইক্রন (7.5 µm)', '৭৫ ন্যানোমিটার (75 nm)', '০.৭৫ মিমি (0.75 mm)', '৭.৫ পিকোমিটার (7.5 pm)'],
    correctIndex: 0,
    explanationBn: 'লোহিত রক্তকণিকার ব্যাস প্রায় ৭.৫ মাইক্রন (১০⁻⁵.¹ মিটার)।',
    targetOrder: -5.12
  },
  {
    questionBn: 'সূর্যের ব্যাস আনুমানিক কত?',
    questionEn: 'What is the approximate diameter of the Sun?',
    options: ['১৩.৯ লক্ষ কিলোমিটার', '১.৩৯ লক্ষ কিলোমিটার', '১৩.৯ কোটি কিলোমিটার', '১,৩৯০ কিলোমিটার'],
    correctIndex: 0,
    explanationBn: 'সূর্যের ব্যাস প্রায় ১৩.৯ লক্ষ কিলোমিটার (১.৩৯ × ১০⁹ মিটার)।',
    targetOrder: 9.14
  },
  {
    questionBn: 'প্রকৃতির অবিভাজ্য তাত্ত্বিক সর্বনিম্ন সীমা বা প্ল্যাঙ্ক দৈর্ঘ্য কত?',
    questionEn: 'What is the theoretical Planck length limit?',
    options: ['১.৬১৬ × ১০⁻৩৫ মিটার', '১.০ × ১০⁻১৮ মিটার', '৩.৩ × ১০⁻৪৪ মিটার', '১.৬১৬ × ১০⁻১৫ মিটার'],
    correctIndex: 0,
    explanationBn: 'প্ল্যাঙ্ক দৈর্ঘ্য হলো ১.৬১৬ × ১০⁻৩৫ মিটার।',
    targetOrder: -34.79
  },
  {
    questionBn: 'আকাশগঙ্গা গ্যালাক্সির ব্যাস আনুমানিক কত আলোকবর্ষ?',
    questionEn: 'What is the approximate diameter of the Milky Way galaxy?',
    options: ['১ লক্ষ আলোকবর্ষ', '১ কোটি আলোকবর্ষ', '১০,০০০ আলোকবর্ষ', '৯৩ বিলিয়ন আলোকবর্ষ'],
    correctIndex: 0,
    explanationBn: 'আকাশগঙ্গার ব্যাস প্রায় ১ লক্ষ আলোকবর্ষ (৯.৫ × ১০²⁰ মিটার)।',
    targetOrder: 21.0
  }
];
